### DISCUSSION TITLE
Improving JSON Schema Compatibility

### DISCUSSION THREAD

**Discussion by JBBianchi** [serverlessworkflow/specification#1093] [General]
Currently, we use a combination of `$ref` and `properties` to inherit from internal definitions, as described in this [JSON Schema blog post](https://json-schema.org/blog/posts/modelling-inheritance).

For example, each task inherits from `taskBase`, as shown in the [`set` task](https://github.com/serverlessworkflow/specification/blob/0ceb0e373334eb224726702df8070cfdc77cff19/schema/workflow.yaml#L761-L776 ):
```yaml
 setTask: 
   type: object 
   $ref: '#/$defs/taskBase' 
   title: SetTask 
   description: A task used to set data. 
   required: [ set ] 
   unevaluatedProperties: false 
   properties: 
     set: 
       oneOf: 
         - type: object 
           minProperties: 1 
           additionalProperties: true 
         - type: string 
       title: SetTaskConfiguration 
       description: The data to set. 
```

I believe this approach relies on a feature introduced (or at least refined) in JSON Schema draft 2020-12. While this version is already a few years old, it is not yet widely supported by some tools. I have encountered compatibility issues in two different contexts:

- VS Code https://github.com/microsoft/vscode-json-languageservice/issues/260#issuecomment-2766373288
- json-schema-to-typescript https://github.com/bcherny/json-schema-to-typescript/issues/613

A possible workaround would be to use `allOf` to inherit from a schema instead. For the `set` task, this would look like:
```yaml
setTask:
   type: object 
   title: SetTask 
   description: A task used to set data. 
   required: [ set ] 
   unevaluatedProperties: false 
   allOf:
   - "$ref": "#/$defs/taskBase"
   - properties:
       set:
          oneOf: 
          - type: object 
            minProperties: 1 
            additionalProperties: true 
          - type: string 
          title: SetTaskConfiguration 
          description: The data to set. 
```

This change should not affect tools that already support the current approach but could improve compatibility—particularly with VS Code, which is required for [draft PR](https://github.com/serverlessworkflow/vscode-extension/pull/33).

Would this be an acceptable improvement for broader tool support? I'm curious to hear your thoughts!
