### DISCUSSION TITLE
Proposal to update `run:shell:arguments` definition

### DISCUSSION THREAD

**Discussion by JBBianchi** [serverlessworkflow/specification#1094] [General]
Hello, dear community,

I'd like to bring up a small concern regarding the definition of [run:shell](https://github.com/serverlessworkflow/specification/blob/main/dsl-reference.md#shell-process). 

Currently, the `arguments` property is defined as a **map**:

arguments | **map** | no | A list of the arguments of the shell command to run
-- | -- | -- | --

While this structure makes sense for [run:script](https://github.com/serverlessworkflow/specification/blob/main/dsl-reference.md#script-process), where arguments represent a set of variables and their values, shell command arguments are typically an [**array**](https://en.wikipedia.org/wiki/Command-line_argument_parsing), not a **key-value map**. 

To align with common usage and improve clarity, I propose updating the documentation and schema for `run:shell:arguments` to use an **array** instead of a **map**. Additionally, the documentation for `run:script:arguments` should be adjusted, as it currently describes the property as:

> "A list of the arguments, if any, of the script to run"

This should be corrected to:

> "An arguments' map, if any, of the script to run"

I’d love to hear your thoughts on this! Would this be an acceptable improvement to better reflect expected behavior?

Looking forward to your feedback!

**Comment by cdavernas** [comment]
@JBBianchi You are perfectly right! While this was intended to simplify expressions for named arguments, this obviously does not work for un-named arguments and flags. Your proposal therefore makes asbolute sense.

I would, however, delay your proposal until we finally addressed the many problems inherent to the `shell` task, such as:
- How can we enforce consistency of shell commands accross platforms/runtimes (i.e. win vs linux)?
- Where are shell commands run when using a FaaS or container based runtime?
...

**Comment by hirenr** [comment]
I am currently doing it like so, and it seems more in line with run.script and run.container too.

Workflow Spec
```
shell:
        command: wget -q -O- $URL
        arguments:
          URL: 'http://ifconfig.io/'
```

and it outputs a multiline script like so in the runtime... which I then execute (I use a container as the default choice for my runtime)!!

```
#!/bin/sh
URL=http://ifconfig.io/
wget -q -O- $URL
```

this seems very intuitive to me!! 

Alternatively, instead of having a separate arguments and command in the shell spec, we could just make command as a string array!

**Comment by ricardozanini** [comment]
@JBBianchi +1.

Also alignes with k8s API pretty nicely: https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/#define-a-command-and-arguments-when-you-create-a-pod

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: command-demo
  labels:
    purpose: demonstrate-command
spec:
  containers:
  - name: command-demo-container
    image: debian
    command: ["printenv"]
    args: ["HOSTNAME", "KUBERNETES_PORT"]
  restartPolicy: OnFailure
```
