### DISCUSSION TITLE
Failing a workflow

### DISCUSSION THREAD

**Discussion by k-jay-c** [serverlessworkflow/specification#698] [Ideas] [answered]
Is it possible to "Fail" a workflow based on a given condition?  e.g.  I could have an API that gives me a status.  Based on the value of that status, I want to decide that if the status returned is "XYZ", for this particular workflow, the workflow should fail.  

I searched the specification, and couldn't see this was possible and think this would be a good feature to support.

**Comment by tsurdilo** [comment]
Can you give more info on your use case? 

> I could have an API that gives me a status.

is this status a value that should come from the workflow execution, like a query for parts of workflow data? 
If so, iirc i brought up this feature in the past and people did not see value in it, to me personally this would be an awesome feature to add, but majority of community saw it as something runtimes should expose and not the spec itself. 
Right now to "query" your workflow code would need to wait for a "query event" and then send the response as an event back to the caller. 

> for this particular workflow, the workflow should fail

So are you looking for some api that would allow you to trigger cancellation / compensation or termination of your workflow execution?
This is indeed typically something that runtimes should expose and not spec in particular imo.
I do see the benefit of exposing "hooks" similar to before mentioned query feature from the workflow definition itself however.

Think best way would be to open some feature requests for these things and then see where the discussions go. Thanks.

**Reply by k-jay-c** [reply]
So, see below sample YAML:

``` YAML
id: Sample Workflow
version: "1.0"
specVersion: "0.9"
name: Sample
description: Sample
start: begin
functions:
  - name: GetStatus
    operation: GetStatus
  - name: UpdateObject
    operation: UpdateObject
  
states:
  - name: begin
    type: operation

    actions:
      - name: GetServiceStatus
        functionRef:
          refName: GetStatus
          arguments:
            key: value 
        actionDataFilter:
          toStateData: "${ .status }"
    transition: 
      end: evaluateStatus
  - name: evaluteStatis 
    type: switch 
    dataConditions:
      - name: shouldUpdate
        condition: ${ .status == "XXX"  }
        transition:
          nextState: DoUpdate
      - name: failStatus 
        condition: ${ .status == "YYY"  }
        transition:
          end: true
          #Fail here, with a reason.  
    defaultCondition:
      end:
        terminate: true 
        
  - name: DoUpdate
    type: operation 
    actions:
      - name: doUpdate 
        functionRef:
          refName: UpdateObject
          arguments:
            key: value
        actionDataFilter:
          toStateData: "${ .updateResult }"
    transition: 
      end: true

```

I have an API, getStatus, returns a value.  There is no way to fail this workflow if my status returns a specific value which is not valid for my workflow.  The workflow author should have the ability to define it's failure conditions which are based on data.
