### DISCUSSION TITLE
Change Do: so it uses the same structure everywhere

### DISCUSSION THREAD

**Discussion by fjtirado** [serverlessworkflow/specification#872] [Ideas]
Currently we have two different schemas for do:, depending on the position of the keyword. 
When used in the main flow, do: is a non empty map of name and task, effectively allowing usage of multiple sequential named task, as [here](https://github.com/serverlessworkflow/specification/blob/main/ctk/features/flow.feature#L10-L22)
When used in a loop and in a retry do: is a task. If you want to to use sequential multiple task you have to use [composition](https://github.com/serverlessworkflow/specification/blob/main/ctk/features/composite.feature#L14-L26). 
The reason is that the author of the spec feel that usually loop and retry will be single task while main flow will be multi task. Although thats probably true, I believe the same do: structure can be used in all places. The idea, as expressed in the [PR](https://github.com/serverlessworkflow/specification/pull/869), is that do: allow both single unnamed task (single task does not require a name to be univocally identified) and named multiple task. 
This will add the possibility to use an unnamed single task in main workflow and multiple named task in loop, without the need to recur to composition, which is intended to be used when you need more control over your flow. 
So, single task workflow
```
document:
   
do: 
   asingletaskverylikleynamedastheworkflow: 
       call: http

```
can be written (if desired) as
```
document:
   do: 
      call: http
```

While multile task for loop, currently written as

```
 do:
      forEachNumber:
        for:
          each: number
          in: '.number'
        do:
          execute: 
            sequentially:
               increase:
                   set:
                       result: ${.number+1}
                double:
                       set:
                           result: ${ .result*2}
```
can be written as

```
 do:
    for:
       each: number
        in: '.number'
     do:
        increase:
          set:
             result: ${.number+1}
        double:
           set:
             result: ${ .result*2}

```

**Comment by fjtirado** [comment]
Also, current schema allows writing: 
```
document:
 
do: 
   call: 
       call: http
```
which I would say we should try to prevent to avoid confussion, if possible.
