### DISCUSSION TITLE
Make tasks names optional

### DISCUSSION THREAD

**Discussion by JBBianchi** [serverlessworkflow/specification#886] [Ideas]
As the result of #875, the idea of having named properties to describe tasks, such as:
```yaml
document:
   #...
do: 
   task1:
      call: http
      with:
        endpoint: 
          uri: https://fake-endpoint.com/task1
   task2:
      call: http
      with:
        endpoint: 
          uri: https://fake-endpoint.com/task2
   task3:
      call: http
      with:
        endpoint: 
          uri: https://fake-endpoint.com/task3
```

has been dropped because neither JSON not YAML have guaranteed properties ordering. The workflow above could be parsed with the property `task3` before `task2`. With implicit `then`, it would result in the unwanted execution of `task3` before `task2`.

Therefore, to insure the ordering of the tasks, we'll have to rely on an array instead. For instance (in accordance with #872 and #884):
```yaml
document:
   #...
do: 
  sequentially :
    - task1:
        call: http
        with:
          endpoint: 
            uri: https://fake-endpoint.com/task1
    - task2:
        call: http
        with:
          endpoint: 
            uri: https://fake-endpoint.com/task2
    - task3:
        call: http
        with:
          endpoint: 
            uri: https://fake-endpoint.com/task3
```

This raises again another point already mentioned by #869 which is to leave names optional and have something like this instead:
```yaml
document:
   #...
do: 
  sequentially :
    - call: http
      with:
        endpoint: 
          uri: https://fake-endpoint.com/task1
    - call: http
      with:
        endpoint: 
          uri: https://fake-endpoint.com/task2
    - call: http
      with:
        endpoint: 
          uri: https://fake-endpoint.com/task3
```

If more flow control is needed, names can be provided:
```yaml
document:
   #...
do: 
  sequentially :
    - switch:
        case1:
          when: .foo == "foo"
          then: task1
        case1:
          when: .foo == "bar"
          then: task2
      then: task3
    - call: http
      name: task1
      with:
        endpoint: 
          uri: https://fake-endpoint.com/task1
    - call: http
      name: task2
      with:
        endpoint: 
          uri: https://fake-endpoint.com/task2
    - call: http
      name: task3
      with:
        endpoint: 
          uri: https://fake-endpoint.com/task3
```

What's your take @cdavernas @fjtirado @matthias-pichler-warrify @ricardozanini ?

**Comment by cdavernas** [comment]
We already reached a consensus to go with:

```yaml
do:
  - myTaskName:
      call: ...
```

Like Google Workflows.

Your second proposal is the same than not having names. If they are optional, noone will use them, ever. Also, it hinders fluency imo.
