### DISCUSSION TITLE
Implementation specific context

### DISCUSSION THREAD

**Discussion by matthias-pichler** [serverlessworkflow/specification#932] [Ideas] [answered]
# Idea

Runtime expressions already specify a list of [Arguments](https://github.com/serverlessworkflow/specification/blob/main/dsl.md#runtime-expression-arguments) that are available. These are all defined by:

1) the workflow definition (`$task`, `$workflow`) 
2) the execution input (`$input`, `context`)
3) secrets (`$secrets`)

If I were to take my workflow and move it from one implementation to another I would expect that all these are exactly the same since they are implementation agnostic. 

I propose to add a new argument called `$runtime` (alternative names could be `$implementation` or `$engine`) that can be filled with implementation runtime specific context such as:

- `tenantId`, `accountId`, `organization`: useful for SaaS platforms using serverless workflow
- `version`: the version of the runtime (e.g. `0.4.8`)
- `runtimeName`: the name of the implementation (e.g. `Synapse`, `Sonanta`)
- `dryRun`, `featureFlags`: for implementation specific features such as

# Why is this needed

I have a case where I want workflow authors to be able to access their tenantId in every workflow as well as the fact if this is a test run.

using a specified expression argument like `$runtime` allows to quickly identify which workflows rely on implementation specific information and which are fully platform agnostic.

# Alternatives

## Non standard argument

Nothing is stopping implementors to expose a non standard argument like `$runtime` or `$impl` to their authors. This argument however would be harder to spot if it differs between implementations. 

## Secrets

All these things could be exposed using secrets. However:

- some of them are not secrets which makes this weird
- authors would have to specify them under `use` every time
- it does not carry the information that these are platform dependant

## extending `$context`

Some runtimes might choose to extend the existing `$context` argument which would mean that the content of `$context` would differ from the result of the last `export.as` and if not expected could send invalid data in tasks

```yaml
document: {}
do:
  - getPet:
      call: http
      with: {}
      export:
        as:
          petId: ${ .pet.id }
  - adoptPet:
      call: http
      with:
        body: ${ $context } # this would then suddenly contain unexpected data such as `$context.runtime.tenantId`
```
