### DISCUSSION TITLE
Default output and error behavior for call:http,openapi,grpc

### DISCUSSION THREAD

**Discussion by matthias-pichler** [serverlessworkflow/specification#978] [General] [answered]
Currently the default output behavior for the `call: http` task is `content` which returns the content (i.e. body) of the response. This is very convenient since authors most likely want the response data. However it is very unintuitive when the API returns an error. Since `jq` will happily return `null` if non existing properties are accessed subsequent tasks might seem to work or the workflow might fail many steps downstream. Should we update the ergonomics around error handling?

1. Should `call: http` raise an error if a not-ok (outside of [200, 399]) status is reported?
1. Should the default output type be changed to `response` to report the whole response?
1. should we allow to specify an expected status (range)?

**Comment by cdavernas** [comment]
1. As far as I understand it, a `communication` error should be raised for non-success status code, with the `detail` being the body of the response, and the `status` being the response's status code. At least, it's what we're doing in Synapse.
2. My take on it is no, we shouldn't operate such transformation implicitly IMHO
3. Why not, good idea!

On a side note, this discussion also applies to OpenAPI and GRPC afaik.

**Reply by JBBianchi** [reply]
I agree with 1 & 2. 
For 3, I'm not sure I understand the scope. I think it's valid at the `try..catch` level (I guess using `when`/`exceptWhen`), but I don't think it should be parameter of `call`. (A trickier one at the `call` level are the redirects, should we always follow them or enable a way to throw)

**Reply by matthias-pichler** [reply]
for 3) it wouldn't be at `call` level but inside `with` like

```yaml
document: {}
do:
  - apiCall:
      call: http
      with:
        method: GET
        headers: {}
        endpoint: https://example.com
        expectedStatus: 200-204, 304, 307 # or something like it
```
