### ISSUE TITLE
Document join behavior of `fork` task

### ISSUE THREAD

**Issue by matthias-pichler** [serverlessworkflow/specification#1012]
# `fork` & `join`

Similar to `fork()` in programming there is an implicit notion of `join()` in the workflow DSL. Namely when all branches (of a non-competing fork) finish:

```yaml
document: {}
do:
  - forkExample:
      branches:
        - a: {}
        - b:
            do:
              - b1: {}
              - b2: {}
        - c: {}
  - d: {}
```

The corresponding state diagram would look like this:

```mermaid
stateDiagram-v2
    state fork_state <<fork>>
    state join_state <<join>>

    [*] --> fork_state
    fork_state --> a
    fork_state --> b1
    fork_state --> c

    b1 --> b2

    a --> join_state
    b2 --> join_state
    c --> join_state
    join_state --> d
    d --> [*]
```

Here the first bar represent a `fork` and the second a `join`. Task `d` would only run after `a`, `b1`, `b2` and `c` have finished.

However the current state of the specification does not enumerate all cases, or at least leaves a lot implicitly defined:

## `then` in neighboring branch

The following definition jumps from one (`b`) branch to another (`a`):

```yaml
document: {}
do:
  - forkExample:
      branches:
        - a: 
            do:
              - a1: {}
              - a2: {}
        - b:
            do:
              - b1:
                  then: a2
  - d: {}
```

```mermaid
stateDiagram-v2
    state fork_state <<fork>>
    state join_state <<join>>

    [*] --> fork_state
    fork_state --> a1
    fork_state --> b1

    state "a2" as a2_l
    state "a2" as a2_r

    b1 --> a2_l
    a1 --> a2_r

    a2_l --> join_state
    a2_r --> join_state
    join_state --> d
    d --> [*]
```

In my understanding this would execute task `a2` twice and proceed after both branches have finished. Or should something like this be disallowed?

## `then` outside of `fork`

Another case is when a task outside of `fork` is referenced in `then`. Here `b` references `d`

```yaml
document: {}
do:
  - forkExample:
      branches:
        - a: 
            do:
              - a1: {}
              - a2: {}
        - b:
            then: d
  - d: {}
  - e: {}
```

```mermaid
stateDiagram-v2
    state fork_state <<fork>>
    state join_state <<join>>

    [*] --> fork_state
    fork_state --> a1
    fork_state --> b

    a1 --> a2

    state "d" as d_in
    state "e" as e_in

    a2 --> join_state
    b --> d_in
    d_in --> e_in
    e_in --> join_state
    join_state --> d
    d --> e
    e --> [*]
```

In my understanding this would execute the whole chain of `d --> e` twice as illustrated in the state diagram but the second run of `d` & `e` would wait for both branches to be done

**Comment by cdavernas** [comment]
> The following definition jumps from one (b) branch to another (a):

That is not possible. The flow is invalid as `a2` does not exist in the scope of the `do` of the `b` branch

> Another case is when a task outside of fork is referenced in then. Here b references d

That is not possible. The flow is invalid as `d` does not exist in the scope of the `b` branch.

**Comment by matthias-pichler** [comment]
@cdavernas 
> That is not possible. The flow is invalid as a2 does not exist in the scope of the do of the b branch

ok makes sense to me, should this be allowed?

```yaml
document: {}
do:
  - forkExample:
      branches:
        - a: 
            do:
              - a1: {}
              - a2: {}
        - b:
             then: a
  - d: {}
```
