### ISSUE TITLE
Schema format validation inconsistencies

### ISSUE THREAD

**Issue by cdavernas** [serverlessworkflow/specification#1017]
**What seems off**:

Impossibility to consistently validate workflows using the [v1.0.0-alpha3 schema](https://github.com/serverlessworkflow/specification/blob/main/schema/workflow.yaml) due to validation inconsistencies and/or lack of `format` validation, resulting in multiple schema matches.

**What you expected to be**:

To properly and consistently validate (valid) workflows against the DSL schema

**How to reproduce**:

Given a simplified JSON schema:

```yaml
"$schema": https://json-schema.org/draft/2020-12/schema
"$defs":
  runtimeExpression:
    type: string
    title: RuntimeExpression
    description: A runtime expression.
    pattern: "^\\s*\\$\\{.+\\}\\s*$"
  endpoint:
    title: Endpoint
    description: Represents an endpoint.
    oneOf:
    - "$ref": "#/$defs/runtimeExpression"
    - title: LiteralEndpoint
      type: string
      format: uri-template
    - title: EndpointConfiguration
      type: object
      unevaluatedProperties: false
      properties:
        uri:
          title: EndpointUri
          description: The endpoint's URI.
          oneOf:
          - "$ref": "#/$defs/runtimeExpression"
            title: ExpressionEndpointURI
            description: An expression based endpoint's URI.
          - title: LiteralEndpointURI
            description: The literal endpoint's URI.
            type: string
            format: uri-template
      required:
      - uri
additionalProperties: false
properties:
  address:
    "$ref": "#/$defs/endpoint"
required:
- address
```

It's impossible to consistently validate the following values, even though they are all supposed to be valid:

```yaml
address: 'https://www.google.com/'
```

```yaml
address: '${ .foobar }'
```

```yaml
address: 'https://www.petstore.com/getById/{petId}'
```

| Validator                | <pre>https://www.google.com/</pre> | <pre>${ .foobar }</pre> | <pre>[https://www.petstore.com/getById/{petId}](https://www.petstore.com/getById/%7BpetId%7D)</pre> | <pre>Non URI value</pre> |
|:-------------------------|:----------------------:|:------------:|:---------------------------------------:|:-------:|
| [jschon.dev ](https://jschon.dev/schema)               | `valid`                  | `invalid`      | `valid`                                   | `valid`   |
| [json-everything.net ](https://json-everything.net/json-schema/)      | `invalid`                | `valid`        | `invalid`                                | `invalid` |
| [jsonschemavalidator.net](https://www.jsonschemavalidator.net/)   | `valid`                  | `valid`        | `valid`                                   | `valid`  |

**Proposed fix:**

Remove the `runtimeExpression` and all its references from the schema, transforming `oneOf` alternatives that include it into plain `string`, formatless properties.
