### ISSUE TITLE
Improve CatchErrors schema definition

### ISSUE THREAD

**Issue by fjtirado** [serverlessworkflow/specification#1036]
Currently CatchError definition is an object, which allows specifying anything here
However the idea is that the schema just support definitions of the form
```
catch:
        errors:
          with:
            type: https://serverlessworkflow.io.io/dsl/errors/types/communication
            status: 404
```
where elements under `with:` are of the same name than in `error:` definition, but optional
