### ISSUE TITLE
The context set within the try-catch block is not accessible.

### ISSUE THREAD

**Issue by anushapai23** [serverlessworkflow/specification#1039]
**What seems off**:
The context that is exported within the try and catch block is not accessible in the next task.
 The context that is set within the try-catch block is not accessible from evaluateReportGenerationStatus

```
- generateReport:
    try:
    - chooseReport:
        switch:
        - caseReport:
            when: param1 == "abc"
            then: generateReport
    - generateReport:
        call: openapi
        with:
          document:
            endpoint: https://xyz.com/openapi.json
          operationId: abcvd
          parameters:
            body:
              param1: cyz
              param2: abc
          authentication:
            use: xyz
        export:
          as: '$context + { feedbackReport: . }'
    - setSuccessFlag:
        set:
          isReportGenerated: "true"
        export:
          as: $context + .
    catch:
      errors:
        with:
          type: https://serverlessworkflow.io/dsl/errors/types/communication
          status: 400
      as: error
      do:
      - setErrorFlag:
          set:
            isReportGenerated: "false"
          export:
            as: '$context + . + { error : ($error.detail | fromjson).detail }'
- notifyReportCompletionStatus:
    do:
    - evaluateReportGenerationStatus:
        switch:
        - caseTrue:
            when: $context.isReportGenerated == "true"
            then: notifySuccesfulReportGeneration
        - caseFalse:
            when: $context.isReportGenerated == "false"
            then: notifyUnsuccesfulReportGeneration
        - default:
            then: end

```
