### ISSUE TITLE
Redefine AsyncAPI call

### ISSUE THREAD

**Issue by cdavernas** [serverlessworkflow/specification#1045]
### What would you like to be added?

Redefine AsyncAPI call, which is missing crucial properties to make it work as expected

### Properties

| Name | Type | Required | Description |
|:-------|:------:|:----------:|:--------------|
| document | [`externalResource`](#external-resource) | `yes` | The AsyncAPI document that defines the [operation](https://www.asyncapi.com/docs/reference/specification/v3.0.0#operationObject) to call. |
| channel | `string` | `yes` | The name of the channel on which to perform the operation. The operation to perform is defined by declaring either `message`, in which case the [channel](https://v2.asyncapi.com/docs/reference/specification/v2.6.0#channelItemObject)'s `publish` operation will be executed, or `subscription`, in which case the [channel](https://v2.asyncapi.com/docs/reference/specification/v2.6.0#channelItemObject)'s `subscribe` operation will be executed.<br>*Used only in case the referenced document uses AsyncAPI `v2.6.0`.*  |
| operation | `string` | `yes` | A reference to the AsyncAPI [operation](https://www.asyncapi.com/docs/reference/specification/v3.0.0#operationObject) to call.<br>*Used only in case the referenced document uses AsyncAPI `v3.0.0`.*  |
| server | [`serverDefinition`](#async-api-server-definition) | `no` | An object used to configure to the [server](https://www.asyncapi.com/docs/reference/specification/v3.0.0#serverObject) to call the specified AsyncAPI [operation](https://www.asyncapi.com/docs/reference/specification/v3.0.0#operationObject) on.<br>If not set, default to the first [server](https://www.asyncapi.com/docs/reference/specification/v3.0.0#serverObject) matching the operation's channel. |
| protocol | `string` | `no` | The [protocol](https://www.asyncapi.com/docs/reference/specification/v3.0.0#definitionsProtocol) to use to select the target [server](https://www.asyncapi.com/docs/reference/specification/v3.0.0#serverObject). <br>Ignored if `server` has been set.<br>*Supported values are:  `amqp`, `amqp1`, `anypointmq`, `googlepubsub`, `http`, `ibmmq`, `jms`, `kafka`, `mercure`, `mqtt`, `mqtt5`, `nats`, `pulsar`, `redis`, `sns`, `solace`, `sqs`, `stomp` and `ws`* |
| message  | [`messageDefinition`](#async-api-message-definition) | `no` | An object used to configure the message to publish using the target operation.<br>*Required if `subscription` has not been set.* |
| subscription | [`subscriptionDefinition`](#async-api-subscription-definition) | `no` | An object used to configure the subscription to messages consumed using the target operation.<br>*Required if `message` has not been set.*  |
| authentication | `string`<br>[`authentication`](#authentication) | `no` | The authentication policy, or the name of the authentication policy, to use when calling the AsyncAPI operation. | 

#### Publish

```yaml
call: asyncapi
with:
  document:
    endpoint: https://fake.com/docs/asyncapi.json
  operation: greet
  server:
    name: greetingsServer
    variables:
      environment:  dev
  message:
    payload:
      greetings: Hello, World!
    headers:
      foo: bar
      bar: baz
```

#### Subscribe

```yaml
call: asyncapi
with:
  document:
    endpoint: https://fake.com/docs/asyncapi.json
  operation: chat-inbox
  protocol: http
  subscription:
    correlation: ${ . == $workflow.input.chat.roomId } 
    consume:
      amount: 5
      for:
        seconds: 10
      while: ${ ($context.messages | length) < 5 }
      until: ${ ($context.messages | length) == 5 }
```

## AsyncAPI Server Definition

| Name | Type | Required | Description |
|:-------|:------:|:----------:|:--------------|
| server.name | `string` | `yes` | The name of the [server](https://www.asyncapi.com/docs/reference/specification/v3.0.0#serverObject) to call the specified AsyncAPI operation on. |
| server.variables | `object` | `no` | The target [server's variables](https://www.asyncapi.com/docs/reference/specification/v3.0.0#serverVariableObject), if any. |

## AsyncAPI Message Definition

| Name | Type | Required | Description |
|:-------|:------:|:----------:|:--------------|
| message.payload | `object` | `no` | The message's payload, if any. |
| message.headers | `object` | `no` | The message's headers, if any. |

## AsycnAPI Subscription Definition

| Name | Type | Required | Description |
|:-------|:------:|:----------:|:--------------|
| subscription.correlation | `string` | `no` | A [runtime expression](dsl.md#runtime-expressions), if any, used to filter consumed messages based on their [correlation id.](https://www.asyncapi.com/docs/reference/specification/v3.0.0#correlationIdObject). |
| subscription.consume | [`subscriptionLifetimeDefinition`](#async-api-subscription-lifetime-definition) | `yes` | An object used to configure the subscription's lifetime. |
| subscription.consume.amount | `integer` | `no` | The amount of messages to consume.<br>*Required if `while` and `until` have not been set.* |
| subscription.consume.for | [`duration`](#duration) | `no` | The [`duration`](#duration) that defines for how long to consume messages. |
| subscription.consume.while | `string` | `no` | A [runtime expression](dsl.md#runtime-expressions), if any, used to determine whether or not to keep consuming messages.<br>*Required if `amount` and `until` have not been set.* |
| subscription.consume.until | `string` | `no` | A [runtime expression](dsl.md#runtime-expressions), if any, used to determine until when to consume messages.<br>*Required if `amount` and `while` have not been set.* |

### Community Notes

* Please vote by adding a 👍 reaction to the feature to help us prioritize.
* If you are interested to work on this feature, please leave a comment.
