### ISSUE TITLE
Enhance Set Task to Support Direct Runtime Expressions

### ISSUE THREAD

**Issue by nyamathshaik** [serverlessworkflow/specification#1087]
### What would you like to be added?

The `set` task currently only supports objects for setting values. This issue proposes an enhancement to allow `set` to also accept direct runtime expressions.

### Proposal(s)
- Modify the `set` task **Type** to support both `object` and `string`.
- Update the **Description** to clarify that `set` can be an object or a direct runtime expression.
- Add a new **Example** demonstrating a direct runtime expression.

```yaml
document:
  dsl: '1.0.0'
  namespace: test
  name: set
  version: '0.1.0'
schedule:
  on:
    one:
      with:
        type: io.serverlessworkflow.samples.events.trigger.v1
do: 
  - set:
      set: ${ $workflow.input[0] }
```

### Community Notes

* Please vote by adding a 👍 reaction to the feature to help us prioritize.
* If you are interested to work on this feature, please leave a comment.
