### ISSUE TITLE
Workflow composability with external workflow registries

### ISSUE THREAD

**Issue by ksanderer** [serverlessworkflow/specification#1107]
### What would you like to be added?

I'm building a TypeScript-based Serverless Workflow runtime for short-lived workflows and need guidance on implementing **workflow composability** with external workflow sources. Currently, the `run.workflow` task requires hardcoded `namespace`, `name`, and `version` properties, but I need to fetch workflows from external registries (S3, Git, etc.).

### Use Case

Enable workflows to reference and execute other workflows stored in external registries, similar to how container orchestrators pull images from different registries.

**Current Challenge**: The spec's `run.workflow` task doesn't provide a clear path for external workflow resolution:

```yaml
# Current spec - works for local/known workflows
run:
  workflow:
    namespace: payments
    name: validate-credit-card
    version: '1.2.0'
```

### What I'm Trying to Achieve

I need workflows to fetch from configured registries. Here's what I'm working toward:

```yaml
document:
  dsl: '1.0.0'
  namespace: payments
  name: order-processing
  version: '1.0.0'

use:
  workflowRegistries: # I know there is no such thing in the spec, just an illustration
    acmeProd:
      type: s3
      bucket: acme-workflows-prod
      region: us-east-1
      credentials: ${ $secrets.aws_credentials }
    
    acmeDev:
      type: git
      repository: https://github.com/acme/dev-workflows
      auth: ${ $secrets.github_token }

do:
  # Fetch from S3 registry
  - validatePayment:
      run:
        workflow:
          namespace: 'acmeProd://payments'  # {registry}://{namespace}
          name: 'validate-credit-card'
          version: '1.2.0'
          input: ${ .payment_info }
  
  # Fetch from Git registry
  - processOrder:
      run:
        workflow:
          namespace: 'acmeDev://payments'
          name: 'process-order'
          version: 'latest'
          input: ${ .order }
```

---

### Questions

1. What would be the most spec-compliant way to achieve this?
   - URI-style namespace prefixes (`registry://namespace`, `s3://{registry}/{namespace}`)?
   - Possible we can extend [External resources](https://github.com/serverlessworkflow/specification/blob/main/dsl-reference.md#external-resource) to support workflows? 
   - Extensions to the `run.workflow` task?

3. **Am I missing something?** Are there existing patterns in the spec that could solve this that I haven't discovered?

4. **Implementation guidance?** I would be glad for any guidance or insights on how to implement this feature.

#### Why This Matters

This would enable:
- **Workflow reusability** across teams and projects
- **Version management** of shared workflows
- **Secure workflow distribution** via private registries
- **GitOps workflows** where workflows are stored in version control

I'd greatly appreciate any guidance, pointers to existing solutions, or thoughts on how others have approached this challenge!

### Community Notes

* Please vote by adding a 👍 reaction to the feature to help us prioritize.
* If you are interested to work on this feature, please leave a comment.

**Comment by ricardozanini** [comment]
OMG, I lost track of this one. Are you still working on the TypeScript runtime? I think this is a great way to improve the specification and looking up for workflows remotely makes a lot of sense to me. For authentication, you can reuse the `auth` we already have defined here: https://github.com/serverlessworkflow/specification/blob/main/dsl-reference.md#authentication

Do you mind sending a PR, so we can follow up with examples and a real change to the schema? Sorry again for being late.

**Comment by ricardozanini** [comment]
Thanks for raising this @ksanderer — workflow composability with external sources is a valid need. After reviewing the spec's existing constructs, I think we can solve this by extending the **catalog** concept we already have rather than introducing a brand-new registry mechanism.

### The problem with catalogs today

Currently, a catalog is just an endpoint — there's nothing in the schema that tells you *what kind* of resources it serves. You see `call: log:0.5.2@global` and only by convention know that `global` hosts functions. This makes it impossible to extend catalogs to serve other resource types (like workflows) without ambiguity.

### Proposal: typed catalogs

Add a `type` field to the catalog definition so it's self-describing:

```yaml
use:
  catalogs:
    global:
      type: function         # explicit — serves reusable functions
      endpoint:
        uri: https://github.com/serverlessworkflow/catalog
    acme:
      type: workflow         # serves workflow definitions
      endpoint:
        uri: https://workflows.acme.com/registry
        authentication:
          bearer:
            token: ${ $secrets.acme_token }
```

Then `run.workflow` gains an optional `from` field to reference a workflow catalog:

```yaml
do:
  - validatePayment:
      run:
        workflow:
          name: validate-credit-card
          version: '1.2.0'
          from: acme
          input:
            amount: ${ .total }
```

### Benefits

- **Reuses existing infrastructure**: catalogs, endpoints, and authentication are already in the spec — no new top-level concepts needed
- **Self-describing**: runtimes know what a catalog serves, enabling validation at parse time (e.g., `call: foo@acme` fails if `acme` is `type: workflow`, and `run.workflow.from: global` fails if `global` is `type: function`)
- **Backwards compatible**: `type` defaults to `function`, so existing workflow definitions keep working unchanged
- **Extensible**: future resource types (schemas, policies, etc.) can be added without new constructs
- **Minimal schema changes**: add `type` enum to `catalog`, add optional `from` string to `SubflowConfiguration`

### What else would be needed

- Extend the [catalog file structure convention](https://github.com/serverlessworkflow/catalog?tab=readme-ov-file#structure) to define a layout for workflow definitions alongside functions
- Define how `namespace/name/version` maps to the catalog's file structure for workflow resolution
- Potentially support a shorthand syntax similar to functions: `run.workflow: validate-credit-card:1.2.0@acme`

Thoughts? This feels like a manageable scope for 1.1.0 since it builds on what we already have.

cc @cdavernas
