### ISSUE TITLE
Question about timeout definition  in callback state

### ISSUE THREAD

**Issue by xinydev** [serverlessworkflow/specification#199]
**What is the question**:
```
states:
- name: CheckCredit
  type: callback
  start:
    kind: default
  action:
    functionRef:
      refName: callCreditCheckMicroservice
  eventRef: CreditCheckCompletedEvent
  timeout: PT15M
  transition:
    nextState: StartApplication
- name: StartApplication
  type: subflow
  workflowId: startApplicationWorkflowId
  end:
    kind: default

```
two scenarios  
1. The CreditCheckCompletedEventevent occurs within the defined timeout, the flow runs well and  StartApplication is triggered.
2. The CreditCheckCompletedEventevent does not  occur within the defined timeout, the StartApplication  is still triggered.

My question is how the StartApplication state knows whether the previous state is timeout or not?  because we do not want call a subflow when the previous state is timeout.  Is there some spec like `onErrors` or `default` in callback state?
