### ISSUE TITLE
Replace JSONPath with 'jq'

### ISSUE THREAD

**Issue by alankm** [serverlessworkflow/specification#216]
**What would you like to be added**:

Replace JSONPath with [`jq`](https://stedolan.github.io/jq/) for all [Workflow Data Expressions](https://github.com/serverlessworkflow/specification/blob/master/specification.md#Workflow-Data-Expressions).

**Why is this needed**:

1. JSONPath lacks power and flexibility.

JSONPath was designed to query JSON documents for matches, especially arrays. It wasn't designed to handle complex logic, and the limitations in the spec show. JSONPath's inability to reference parent objects or property names of matching items forces users to contort their data in all sorts of strange ways. 

For example, I wanted to put together a simple workflow that transforms an input from 

```json 
{
	"name": "Alan"
}
```

to 

```json 
{
	"greeting": "Hello, Alan!"
}
```

Here's my solution:

```yaml 
id: helloworld
name: "Hello, World!"
states:
- name: Hello
  type: inject
  data:
    output:
      greeting: "Hello, {{ $.name }}!"
  start:
    kind: default
  end:
    kind: default
  stateDataFilter:
    dataOutputPath: "$.output"
```

It's possible, but it's convoluted. And that's for a simple helloworld. I had to nest my solution in a sub-property named output just so that I could use the stateDataFilter to replace the entire state with the constructed output afterwards. 

If we'd been using `jq` instead of JSONPath, that same solution could look like this:

```yaml
id: helloworld
name: "Hello, World!"
states:
- name: Hello
  type: inject
  start:
    kind: default
  end:
    kind: default
  stateDataFilter:
    dataOutputPath: '{ greeting: ("Hello, " + .name + "!") }'
```

We wouldn't even need the functionality of the Inject State to pull it off. In fact, we could do all of this and more using just stateDataFilters on any state, dramatically simplifying the code.

2. Language Support 

These limitations are well known about JSONPath, which has resulted in a fork of the JSONPath spec called [JSONPath Plus](https://www.npmjs.com/package/jsonpath-plus), which gets >25% more weekly downloads than [the original](https://www.npmjs.com/package/jsonpath).

Unfortunately, JSONPath does not have great language support. JSONPath Plus has even less. For Go I found four different libraries for the former and none for the latter. Of the four libraries, not one produced the correct result in every test I tried over the course of an afternoon. 

By comparison `jq` is relatively less popular amongst JavaScript developers, but seems to have implementations where it matters: languages that will be used to build implementations. 

* [nodejs](https://www.npmjs.com/package/node-jq)
* [go](https://github.com/itchyny/gojq)
* [python](https://pypi.org/project/jq/) [python](https://pypi.org/project/pyjq/)
* [java](https://github.com/eiiches/jackson-jq)

3. JSON Patch 

In my earlier example, nesting the output was necessary to filter it later (due to the aforementioned limitations of JSON Path). But the reason I needed to filter it later is because my requirement was to *replace* the data, not enrich it. 

The current specification doesn't have any good way of dealing with the issue of deleting fields, which has resulted in discussions like [this one](https://github.com/serverlessworkflow/specification/issues/149) where bolting on another solution (JSON Patch) is being considered. 

In [an example from that discussion](https://github.com/serverlessworkflow/specification/issues/149#issuecomment-729217479),  input contains two properties that should be removed (`vegetables` and `snacks`):

```json
{
  "fruits": [ "apple", "orange", "pear" ],
  "drinks": ["capirinha", "whisky", "vodka", "wine"],
  "snacks": ["french fries", "jelly beans"],
  "vegetables": [
    {
      "veggieName": "potato",
      "veggieLike": true
    },
    {
      "veggieName": "broccoli",
      "veggieLike": false
    }
  ]
}
```

The proposed JSON Patch solution is to include the following verbose snippet in the state definition:

```yaml
stateDataTransform:
  dataInputPatch:
  - op: remove
    path: "/snacks"
  - op: remove
    path: "/vegetables"
```

In `jq`, this same problem can be tackled with this concise line in the output filter:

```yaml
dataOutputPath: 'del(.vegetables) | del(.snacks)'
```

JSONPath is only capable of returning arrays and/or subsets of data. JSON Patch can build data, but it's a laborious process. `jq` isn't just for searching or querying data, it can also be used to construct, restructure, combine, or transform data. 

4. Adoption

Why combine two solutions to get less functionality? Especially when `jq` can not only do it all, it has an enormous wealth of users and help information readily available? Hundreds of Stack Overflow questions answered. 

**Summary** 

Compared to JSON Path, `jq` usually produces cleaner workflow definitions, it has greater language support, and it is much easier for users to figure out. All while being far more powerful. In fact, `jq` is so powerful that it would render the Inject State obsolete.
