### ISSUE TITLE
Event/Switch State Refactor

### ISSUE THREAD

**Issue by alankm** [serverlessworkflow/specification#228]
## What would you like to be added:

Remove/rework the existing Event State and Switch state into three new states:

### DataSwitch State

| Parameter | Description | Type | Required |
| --- | --- | --- | --- |
| name | State name | string | yes |
| type | State type | string | yes |
| dataConditions | Defined if the Switch state evaluates conditions and transitions based on state data. | array | yes |
| default | Default transition of the workflow if there is no matching data conditions. Can be a transition or end definition | object | yes |
| start | Is this state a starting state | object | no |

### EventSwitch State

| Parameter | Description | Type | Required |
| --- | --- | --- | --- |
| name | State name | string | yes |
| type | State type | string | yes |
| eventConditions | Defined if the Switch state evaluates conditions and transitions based on arrival of events. | array | yes |
| timeout | Defines the time period to wait for events (ISO 8601 format). For example: "PT15M" (15 minutes), or "P2DT3H4M" (2 days, 3 hours and 4 minutes)| string | no |
| default | Default transition of the workflow if event timeout is reached. Can be a transition or end definition | object | yes |
| start | Is this state a starting state | object | no |

### EventsListener State

| Parameter | Description | Type | Required |
| --- | --- | --- | --- |
| name | State name | string | yes |
| type | State type | string | yes |
| [onEvents](#onEvents-Definition) | Define the events to be consumed | array | yes |
| timeout | Time period to wait for incoming events (ISO 8601 format). For example: "PT15M" (wait 15 minutes), or "P2DT3H4M" (wait 2 days, 3 hours and 4 minutes)| string | no |
| transition | Next transition of the workflow after all the events have been received | object | yes |
| start | Is this state a starting state | object | no |
| end | Is this state an end state | object | no |

NOTE: I've omitted the following fields from the above tables for brevity: `id`, `stateDataFilter`, `onErrors`, `dataInputSchema`, `dataOutputSchema`, `compensatedBy`, `usedForCompensation`, `metadata`.

And here's a modification to the `onEvents` Definition:

### onEvents Definition

| Parameter | Description | Type | Required |
| --- | --- | --- | --- |
| eventRef | References an event in the defined workflow events | string | yes |
| eventDataFilter | Event data filter definition | object | no |

Notice that the `actionMode` and `actions` parameters have been removed, that is intentional. The `eventRefs` was also changed from an array to a string because this whole structure is already in an array.

### 1. The existing Switch State is more complex than it needs to be.

The spec is easier to implement for developers and easier to understand for users reading documentation if the scope of each state is simple and clear. Currently, the Switch State merges two different types of functionality into one, and there is no clear benefit for it. 

This change takes the old Switch State and splits its functionality into the new DataSwitch and EventSwitch states. 

### 2. The existing Event State's 'exclusive' parameter is less powerful than using a Switch.

What's the difference between an event-based switch and an Event State with `exclusive=true`? The switch has more powerful transition behaviour, and the switch cannot perform actions. In a later bullet-point I'll argue that the event state shouldn't perform actions, making it very hard to justify the existing event state with `exclusive=true`. 

This change takes the old Event State and splits its functionality into the new EventSwitch and EventsListener states (excluding the ability to run actions).

### 3. The existing Event State does too much, and it doesn't need to.

Because the existing Event State can perform actions, it is capable of being extremely complicated. This makes it harder to understand for users, a nightmare to implement for backend developers, and a huge pain to track the current status on a frontend with nice UX/UI.

With `exclusive=true`, the existing Event State acts like a way of condensing multiple logically distinct workflows into a single workflow YAML. This is a fun exercise, but a bad quality for the serverless workflow spec to have. 

With `exclusive=false`, the existing Event State is capable of running an unbounded number of actions, some grouped into sequences and others grouped into parallels, all running in a super-parallel group. And it gets even more confusing when actions can become `eventRef` based actions that are now waiting on more events to continue. 

This is an entire workflow built into what should be a simple event listener state. And it's not a simple workflow either. 

Why should an event listener have so much scope-creep? All of the sane uses of this functionality can be replicated by simply transitioning to an Operation State or a Parallel state. Transitioning from state-to-state is the bedrock of a workflow so we should embrace it, rather than trying to crush everything into one Frankenstein's Monster state. 

This change completely removes the ability of the Event State to perform actions.

**Comment by tsurdilo** [comment]
@alankm we do need to have the capability that exclusive=false currently provides. Being able to consume multiple defined events is important in some cases to solve business problems. We should not remove that functionality.

Regarding splitting switch state into two: only diff i see above is one has  dataConditions and the other eventConditions. Whats the big benefit from what's there is now when users can pick one or the other?

Regarding above "EventListener" state: 
1) with how it is defined we would need to allow multiple starting eventlistener states (imo bad idea atm), or update the OnEvents definitions to be able to transition. 
2) for large workflows that consume a large number of events when each events can trigger a set of actions this can exponentially increase the number of lines of json/yaml (the number of states) users would have to define.
instead of having a single event starting state and a single, large, onEvents definition, users would have a single eventlistener state and possibly 100+ operation states. Thats a ton more lines of markup.
For this cases users would also need to coordinate (join) execution of all of these operation states that perform actions which again is a pain. The current event state does alot atm, but imo has a lot less scope creep than using the proposed one in large workflows.

So overall: The switch state split is OK with me if people see it useful. I do not agree with the event state proposed changes as they remove an important piece of functionality and can create a much larger workflow markup in some cases.

**Comment by tsurdilo** [comment]
@alankm also look at the onEvents definitions "actionModel" property as it is currently. I don't know how in your case you envision this to work? I guess an array of operation state references ?

**Comment by tsurdilo** [comment]
@alankm thinking out loud: i could potentially see the case for the EventListener state as an additional state alongside the current event state. A much more simpler state, that is clearly defined as such, for cases where indeed you might be just consuming a single event and transition...wdyt?

**Comment by alankm** [comment]
I think that that the existing scope of the event state is absurd. Can you provide a sane, real-life example where that functionality is necessary? 

The complexity of the event state as it stands makes it so painful to work with that it's halfway unimplementable.

**Comment by tsurdilo** [comment]
@alankm we do have two examples that show off exclusive in the examples: 

1) https://github.com/serverlessworkflow/specification/blob/master/examples/examples.md#handle-car-auction-bids-example (exclusive=true)
2) https://github.com/serverlessworkflow/specification/blob/master/examples/examples.md#finalize-college-application-example (exclusive=false)

**Comment by alankm** [comment]
Having the ability to consume multiple events at once (`exclusive=false`) makes sense. What doesn't make sense is running actions inside the Event State. Sorry if I was unclear: the proposed `EventsListener` state behaves like `exclusive=false`. The difference is that it cannot run any actions, it always just transitions to another state. 

My problem is with the actions, not the way that events are consumed.

**Comment by alankm** [comment]
Both of the examples you've linked would be possible based on my proposal.

**Comment by tsurdilo** [comment]
@alankm by adding exclusive to the proposed eventlistener state..right?
so for example instead of :
"onEvents": [{
        "eventRefs": ["HighBodyTemperature"],
        "actions": [{  ... }] },
       "eventRefs": ["HighBloodPressure"],
        "actions": [{  ... }] }, 

you would have
"onEvents": [{
        "eventRefs": ["HighBodyTemperature"],
        "transition": "abc"
        },
       {
        "eventRefs": ["HighBloodPressure"],
        "transition": "xyz"
        }
        ..... 
?

**Comment by alankm** [comment]
@tsurdilo That's right. 

The main concern is about replacing actions with transitions. Transition to an Operation or a Parallel. 

I also note that the `exclusive` parameter becomes completely unnecessary because it provides overlap with the event-based-switch. So my EventsListener always behaves like the current `exclusive=false`, and if you want `exclusive=true` behaviour you can use EventSwitch instead.

**Comment by tsurdilo** [comment]
@alankm ok i think i get your points better now. we had many discussions about the event state in the past and i would like to see what the team thinks of this, so definitely +1 for bringing this up in meetings to get opinions.

Still want to say that SW takes a declarative approach to workflows (meaning it is really based on its markup). This is quite different than some other graphical-based workflow languages which depend more on things like forms and flow chars to describe business logic.
Not having a graphical representation makes the markup size quite important and we do have include it in decisions as well.
I think for larger workflows the proposed changes can significantly increase the number of lines of json/yaml of the workflow, so maybe finding some middle ground where everyone can be "happy" would be a good approach.

**Comment by alankm** [comment]
@tsurdilo 

To help illustrate the issue I'm having, as far as I can tell the following bit of yaml should be valid... But it would be a very challenging thing to implement. It's no longer a simple parallel or sequence, it's a complex overlap of sequences and parallels inside a parallel, and some of them even produce events and stop and wait to receive more events.

```yaml
events:
- name: EventA
  type: event.a 
  source: mysource
  correlation:
  - contextAttributeName: applicateId 
- name: EventB
  type: event.b 
  source: mysource
  correlation:
  - contextAttributeName: applicateId 
- name: EventD
  type: event.c
  source: mysource
  correlation:
  - contextAttributeName: applicateId 
- name: EventE
  type: event.e 
  source: mysource
  correlation:
  - contextAttributeName: applicateId 
- name: EventF
  type: event.f 
  source: mysource
  correlation:
  - contextAttributeName: applicateId 
- name: EventG
  type: event.g 
  kind: produced
functions:
- name: funcA
  operation: http://myapis.org/a
- name: funcB
  operation: http://myapis.org/b
- name: funcC
  operation: http://myapis.org/c
- name: funcD
  operation: http://myapis.org/d
states:
- name: StartState
  type: event 
  start: true 
  exclusive: false 
  end:
    terminate: true
  onEvents:
  - eventRefs: [EventA]
    actionMode: sequential
    actions:
    - functionRef:
        refName: funcA 
    - functionRef:
        refName: funcB
  - eventRefs: [EventB, EventC]
    actionMode: parallel
    actions:
    - functionRef:
        refName: funcA 
    - functionRef:
        refName: funcC
  - eventRefs: [EventD]
    actionMode: sequential 
    actions:
    - eventRef:
        triggerEventRef: EventF
        resultEvent: EventG
      timeout: P5M 
    - eventRef:
        triggerEventRef: EventF
        resultEvent: EventG
      timeout: P10M 
  - eventRefs: [EventE]
    actionMode: parallel
    actions:
    - eventRef:
        triggerEventRef: EventF
        resultEvent: EventG
      timeout: P5M 
    - eventRef:
        triggerEventRef: EventF
        resultEvent: EventG
      timeout: P10M 
```

In my opinion, all of the actions should be offloaded to other states and/or subflows. And this event state should be simplified down to:

```yaml
events:
- name: EventA
  type: event.a 
  source: mysource
  correlation:
  - contextAttributeName: applicateId 
- name: EventB
  type: event.b 
  source: mysource
  correlation:
  - contextAttributeName: applicateId 
- name: EventD
  type: event.c
  source: mysource
  correlation:
  - contextAttributeName: applicateId 
- name: EventE
  type: event.e 
  source: mysource
  correlation:
  - contextAttributeName: applicateId 
states:
- name: StartState
  type: event 
  start: true 
  exclusive: false 
  transition: ... # this logic is complicated
  onEvents:
  - eventRef: EventA
  - eventRef: EventB
  - eventRef: EventC
  - eventRef: EventD
  - eventRef: EventE
```

**Comment by tsurdilo** [comment]
@alankm so with your proposal and given the first definition above it would be :

```yaml
states:
- name: StartState
  type: event
  start: true
  onEvents:
  - eventRefs:
    - EventA
    transition: OperationStateA
  - eventRefs:
    - EventB
    - EventC
    transition: ParallelStateA # Could be operation state too...
  - eventRefs:
    - EventD
    transition: OperationStateB
  - eventRefs:
    - EventE
    transition: OperationStateC

```

**Comment by alankm** [comment]
@tsurdilo That example has `exclusive=false`, because I think that's the most complicated example. If it was `exclusive=true` it'd look similar to your example but it'd use my proposed EventSwitch state.

Because the example has `exclusive=false` we need to wait for all events, which is what my proposed EventsListener state is for. I *assume* a workflow should always be in exactly one state at a time, therefore we can't put the transition in each onEvents entry separately, there can only be one outro transition (much like the existing Event State).

So in this particularly complex example it'd probably look something like:

```yaml
events:
- name: EventA
  type: event.a 
  source: mysource
  correlation:
  - contextAttributeName: applicateId 
- name: EventB
  type: event.b 
  source: mysource
  correlation:
  - contextAttributeName: applicateId 
- name: EventD
  type: event.c
  source: mysource
  correlation:
  - contextAttributeName: applicateId 
- name: EventE
  type: event.e 
  source: mysource
  correlation:
  - contextAttributeName: applicateId 
- name: EventF
  type: event.f 
  source: mysource
  correlation:
  - contextAttributeName: applicateId 
- name: EventG
  type: event.g 
  kind: produced
functions:
- name: funcA
  operation: http://myapis.org/a
- name: funcB
  operation: http://myapis.org/b
- name: funcC
  operation: http://myapis.org/c
- name: funcD
  operation: http://myapis.org/d
states:
- name: StartState
  type: eventsListener 
  start: true 
  transition: ParallelStateA
  onEvents:
  - eventRef: EventA
  - eventRef: EventB
  - eventRef: EventC
  - eventRef: EventD
  - eventRef: EventE
- name: ParallelStateA
  type: parallel 
  end:
    terminate: true
  branches:
  - name: BranchA
    workflowId: SubflowA
  - name: BranchB
    actions:
    - functionRef:
        refName: funcA 
    - functionRef:
        refName: funcC
  - name: BranchC
    workflowId: SubflowB
  - name: BranchD
    actions:
    - eventRef:
        triggerEventRef: EventF
        resultEvent: EventG
      timeout: P5M 
    - eventRef:
        triggerEventRef: EventF
        resultEvent: EventG
      timeout: P10M 
---
# SubflowA (functions/events omitted)
states:
- name: StartState
  type: eventsListener 
  start: true 
  end: true
  actionMode: sequential
  actions:
  - functionRef:
      refName: funcA 
  - functionRef:
      refName: funcB
---
# SubflowB (functions/events omitted)
states:
- name: StartState
  type: eventsListener 
  start: true 
  end: true
  actionMode: sequential 
  actions:
  - eventRef:
      triggerEventRef: EventF
      resultEvent: EventG
    timeout: P5M 
  - eventRef:
      triggerEventRef: EventF
      resultEvent:
```

Of course, you could use subflows for all four branches, but I mixed in some of the other type to show other options. 

Yes, it effectively *requires* users to break their logic up into subflows. But in this case I think it's justified. This is a very complicated workflow.
