### ISSUE TITLE
Compensation should work no matter what comes next.

### ISSUE THREAD

**Issue by alankm** [serverlessworkflow/specification#280]
# The Problem

Error handling is completely possible without using any of the compensate stuff, just by making good use of switches, but compensation should make life easier for users and make logic clearer in workflow definitions. 

> In our example when compensation is triggered, the current workflow data is passed as input to the "D1" state, the first compensation state for our example. It state data output is then passed as state data input to "B1", and so on.

This comment from the specification is the problem.

Undoing/compensating for something should be possible with the information available right after that thing has occurred, but the further away you get from that thing the more likely your information has changed. Consider this example from the specification:

```yaml
states:
- name: NewItemPurchase
  type: event
  onEvents:
  - eventRefs:
    - NewPurchase
    actions:
    - functionRef:
        refName: DebitCustomerFunction
        arguments:
          customerid: "${ .purchase.customerid }"
          amount: "${ .purchase.amount }"
    - functionRef:
        refName: SendPurchaseConfirmationEmailFunction
        arguments:
          customerid: "${ .purchase.customerid }"
  compensatedBy: CancelPurchase
  transition: SomeNextWorkflowState
- name: CancelPurchase
  type: operation
  usedForCompensation: true
  actions:
  - functionRef:
      refName: CreditCustomerFunction
      arguments:
        customerid: "${ .purchase.customerid }"
        amount: "${ .purchase.amount }"
  - functionRef:
      refName: SendPurchaseCancellationEmailFunction
      arguments:
        customerid: "${ .purchase.customerid }"
```

It would be desirable if this snippet worked in a vacuum. But what if `SomeNextWorkflowState` messes with the `.purchase.amount` or `.purchase.customerid`? The problem becomes unrecoverable. 

Golang has a concept that feels similar to compensate called [defer](https://tour.golang.org/flowcontrol/12), and of note:

> The deferred call's arguments are evaluated immediately, but the function call is not executed until the surrounding function returns.

This ensures that the deferred logic runs the same way no matter what comes afterwards. This is what compensation should aim to achieve. 

# Proposal

Here's my proposal in two parts:

1. When transitioning out of a state that defines a `compensatedBy`, implementations should make a full copy of the state data output and save it somewhere. If the workflow ever triggers this compensation the saved state data output will be given as state data input to the compensation state. 

2. Compensation states' state data output should be discarded after that compensation chain ends. Where else would it go? Should authors be trying to compensate for compensation in the main flow of their logic? No.

Note that this proposal requires potentially a lot of data duplication. Every state that may be compensated each needs its own copy saved just-in-case, until the workflow has finished. That's not great, but I can't see a way around it.

So if we follow the diagrams and examples in the specification:

https://github.com/serverlessworkflow/specification/blob/master/media/spec/compensation-exec.png

https://github.com/serverlessworkflow/specification/blob/master/media/spec/compensation-exec2.png

Here's how state data should be moved around.

* Workflow_input -> A_input
* A_output -> B_input
* B_output -> D_input
* D_output -> E_input
* D_output -> D1_input
* B_output -> B1_input
* B1_output -> B1-2_input
* E_output -> Workflow_output

**Comment by tsurdilo** [comment]
Hi @alankm 
Regarding **Undoing/compensating for something should be possible with the information available right after that thing has occurred, but the further away you get from that thing the more likely your information has changed. ** 

I think this statement is not correct. Let's you have a workflow that is responsible for booking a trip. 
The user books the trip with email address A and address B. Then during later states of this workflow the user changes his/her email (to X) and address (to Y). With what you are describing here you would compensate the "Book Trip" state with email A and address B. That is incorrect imo.

Compensation should occur on the data at which point the compensation is requested. That is the only way to assure its integrity.

**Comment by tsurdilo** [comment]
States used for compensation have the right to alter the state data, as they are also part of the business logic just like any other states. Using the same example as in previous comment, the "CancelPurchase" has every right to execute an action that pulls the latest customer information from a db for example and use that to compensate the purchase with.

**Comment by jensg-st** [comment]
@tsurdilo if that is what the compensation wants to achieve then we don't need that state at all. It can be modeled as a normal flow in my opinion.

**Comment by tsurdilo** [comment]
@jensg-st yes you are right, however what compensation brings is a much easier way for users to describe undo requirements. Imagine having to write compensation logic on a 200+ state workflow.

**Comment by tsurdilo** [comment]
@jensg-st also as its in the spec doc and my video on compensation , writing it with control flow logic alone is sometimes impossible. 
you cannot by control flow logic alone know which paths of the workflow have been taken so far. and writing the logic with states alone would require additional data checks which is often completely not even possible to do

**Comment by tsurdilo** [comment]
https://www.youtube.com/watch?v=Ea8yR-EkrZQ&feature=youtu.be

**Comment by tsurdilo** [comment]
@jensg-st @alankm i think we are thinking two things, one is compensation (undoing something, part of business logic) and you are probably thinking of Saga patterns, where data of a state is persisted (to undo the transaction it self).

**Comment by alankm** [comment]
@tsurdilo 

> Compensation should occur on the data at which point the compensation is requested. That is the only way to assure its integrity.

This will be a nexus of bugs. You're basically saying every state needs to keep in mind every other state (and every state's compensation states) to avoid causing problems.

As pointed out, there's already a way to handle errors without compensate just by modelling the error handling into the flow, so if compensate is going to exist it should be a convenient shorthand to solve a problem that shows up 99% of the time, not a barely distinct alternative to the existing solution.

---

Even leaving aside the issue of UX, this proposal actually makes new things possible. It allows users to strip out data after it stops being relevant. Especially useful when you have for example sensitive tokens/keys that you need for an API call (both to do and undo) and you want to remove them from the flow to reduce the risk of them being exposed somewhere down the line.

**Comment by jorgenj** [comment]
I worry that this proposal excludes some potential compensation use-cases, for example imagine a workflow with several milestones, upon failure it only wants to compensate back until the most recently passed milestone.  With this proposal I believe that would be impossible, since compensation for earlier states would not see the updates that might indicate the most recent milestone reached.

**Comment by tsurdilo** [comment]
**This will be a nexus of bugs. You're basically saying every state needs to keep in mind every other state (and every state's compensation states) to avoid causing problems.** Not really, during workflow execution the runtime needs to keep track of what states have so far been executed. At the point compensation is requested, it needs to replay this and for each executed state (in reverse order) execute its compensation state (if one was defined).

Compensation is not always associated with errors. A business requirement could be to trigger the "undo" for some condition after action execution that is not handled as an error. 

We cannot control from the language perspective how the runtimes will handle transaction boundaries imo. Some runtimes might persist at each state, some might persist at "wait states" only such as event states. 
Depending on the deployment strategies of the workflow (single service per workflow or service per workflow state) the transaction boundaries might be completely different and even controlled by some other service).

I am trying to understand what is needed here better. WDYT?

**Comment by alankm** [comment]
@jorgenj I agree with this. I felt the same way about the existing spec though. Technically the existing spec could handle this I suppose, but I don't think it does so in an intuitive way.

@tsurdilo I don't follow. I don't think the implementation specifics have any impact on the proposal. Nor do I think the value of the proposal changes based on whether compensation is being used to handle errors or otherwise.

**Comment by alankm** [comment]
@jorgenj I think the concept of milestones has value, and should either explicitly become part of the specification (some way to clear all compensations on the stack up until this point), or should just be modelled by users with subflows. Subflows solve this problem.

**Comment by tsurdilo** [comment]
@alankm i am trying to understand the proposal. Asked a question here: https://github.com/serverlessworkflow/specification/issues/280#issuecomment-790143977 which I think pretty much is the reason why I don't understand it. 

Same thing for https://github.com/serverlessworkflow/specification/issues/280#issuecomment-790147122
Please show me how you would undo a workflow with multiple switch states with control flow logic alone when you have 0 clue which path the workflow took to get there?

**Comment by alankm** [comment]
@tsurdilo Can you provide a real-life example? I don't believe you ever need to be stuck in a situation where you have zero clue what needs to be done. Workflows can be modelled as state machines, which means the path it took is irrelevant.

**Comment by tsurdilo** [comment]
@alankm sure ill try very simple one:

sample workflow input:
```yaml
{
    "type": "debit",
    "account": {
        "number": "1234",
        "amount": "100"
    }
}
```

workflow
```yaml
---
id: performtransaction
name: Perform user transaction
start: Check Transaction Type
states:
- name: Check Transaction Type
  type: switch
  dataConditions:
  - condition: ${ .type == "debit"
    transition: Do Debit
  - condition: ${ .type == "credit"
    transition: Do Credit
  stateDataFilter:
    output: "${ .account }"
- name: Do Debit
  type: operation
  actions:
  - functionRef:
      refName: Do Debit Function
      arguments:
        account: "${ .account }"
    actionDataFilter:
      toStateData: "${ .account.balance }"
  transition: Report Results
- name: Do Credit
  type: operation
  actions:
  - functionRef:
      refName: Do Credit Function
      arguments:
        account: "${ .account }"
    actionDataFilter:
      toStateData: "${ .account.balance }"
  transition: Report Balance
- name: Report Balance
  type: operation
  actions:
  - functionRef:
      refName: Report Balance Function
      arguments:
        balance: "${ .account.balance }"
  end: true
```

let's say you want to after " Report Balance Function" compensate this transaction via control flow logic. Since after "Check Transaction Type" you lost the "type" data input and just have the account info (including the balance) how do you know to compensate the credit or the debit operation?

The way compensation is defined in the spec "Do Credit" and "Do Debit" would each have a compensatedBy clause and it would not require you to keep some state data around or worry about not losing data etc.

**Comment by alankm** [comment]
@tsurdilo Are you asking me how I would model this with **no** type of compensation? Or with my proposal for compensation? Because with my proposal all of the following would still be true:

> Do Credit" and "Do Debit" would each have a compensatedBy clause and it would not require you to keep some state data around or worry about not losing data etc.

In fact, with my proposal you could also strip out the `amount` with your transform and it would still run perfectly. (`output: "${ del(.type, .account.amount) }"`. Or you could reuse the "amount" variable and perform this logic in a loop. 

----

If you're asking me how to recover without compensate at all, obviously in this case you can't. But only because this workflow intentionally becomes unrecoverable. A user who encounters this problem would just *not* strip that `amount` field out. It'd become a non-issue with barely a moment's thought.

So what I mean when I'm asking for a real life example is if there's a situation where a user couldn't fix the problem with a trivial tweak to their workflow definition, or has compelling reasons why they don't want to.

**Comment by tsurdilo** [comment]
@alankm what i dont understand is, from this example you provided: 

Workflow_input -> A_input
A_output -> B_input
B_output -> D_input
D_output -> E_input
D_output -> D1_input
B_output -> B1_input
B1_output -> B1-2_input
E_output -> Workflow_output

for that example the last state executed would be "Report Balance". but what if user after compensating wants to "Send Email to Customer Explaining Account Activity" ?

**Comment by alankm** [comment]
@tsurdilo If there was a state "F" in the example?

Instead of the very end saying 

* E_output -> Workflow_output

We'd just say

* E_output -> F_input
* F_output -> Workflow_output

**Comment by tsurdilo** [comment]
@alankm ok :) I think im getting there. last question, during compensation if "Do Debit" was performed user wants to do
E_output_F_input
and if "Do Credit" was performed then 
E_output_G_input
?

**Comment by tsurdilo** [comment]
What I have hard time understanding is how is this different than current compensation? It's probably bets if you explain this  to me in meeting cause apparently I am too tired now to get it :) 

compensation triggered after E_output that needs to perform F would also be E_output_F_output->Workflow_output
if the compensatedBy state is F.

**Comment by alankm** [comment]
@tsurdilo Not sure I understand the question, but I'll try and answer anyway.

```yaml
---
id: performtransaction
name: Perform user transaction
start: Check Transaction Type
states:
- name: Check Transaction Type
  type: switch
  dataConditions:
  - condition: ${ .type == "debit" }
    transition: Do Debit
  - condition: ${ .type == "credit" }
    transition: Do Credit
  stateDataFilter: # deleted this
- name: Do Debit
  type: operation
  actions: # cut for brevity
  transition: E
  compensatedBy: Compensate Debit
- name: Compensate Debit
  type: operation
  usedForCompensation: true
  actions: # cut for brevity
- name: Do Credit
  type: operation
  actions: # cut for brevity
  transition: E
  compensatedBy: Compensate Credit
- name: Compensate Credit
  type: operation
  usedForCompensation: true
  actions: # cut for brevity
- name: E
  type: switch
  dataConditions:
  - condition: ${ .type == "debit" }
    transition: Do 
      nextState: F
      compensate: true
  - condition: ${ .type == "credit" }
    transition: 
      nextState: G
      compensate: true
# TODO: whatever F & G are.
```

---

The only difference between my proposal and the existing solution is what data gets passed to compensate states. I believe a snapshot of the data should be made when a state that *might* need compensating happens so that the data at the moment can be supplied to the compensation state. 

Because I think users should be able to look at a state and its compensate logic in a vacuum and know exactly how they work. And trust that they work even if a hundred other things happen afterwards and their colleague has completely changed the state data.

**Comment by tsurdilo** [comment]
@alankm 
so you are saying for a workflow with a large amount of states, each one declaring its compesation state, and a 1 TB of data input you would persist this data for each state? that makes no sense in a prod environment

**Comment by jorgenj** [comment]
> and a 1 TB of data input you would persist this data for each state?

This is definitely an underlying concern for me, consider a workflow with a 100 states and 100 more corresponding compensation states; even if the runtime restricts workflow data to no more than 256kb that's a pretty large amount of data to retain for each workflow.

> To me thats a runtime issue more than a workflow dsl issue where we only specify the control logic flow.

I'm not sure I understand this.  If some runtimes are doing this and others aren't, then a workflow written for runtime A isn't portable to runtime B which doesn't do compensation that way.

I'm struggling to think of a contrived example to illustrate, but I'm not convinced that in all cases a workflow can be correctly compensated without knowing what steps did or did not run after it.  As in, I can see some cases where this wouldn't be necessary, but I'm struggling to verify that this proposal isn't denying valid compensation use-cases.

@alankm To help me understand something, how about the following contrived workflow.  How might we solve that with the proposal?

```yaml
states: 
  - NotifyUser 
    # let them know we're starting
    transition: DoS1
    compensatedBy: SummarizeFailures
  - DoS1
    transition: DoS2
    compensatedBy: UndoS1
  - DoS2
    transition: SummarizeSuccess
    compensatedBy: UndoS2
  - UndoS2:
  - UndoS1:
  - SummarizeFailures
     # notify the user that we failed at whichever state
```

I apologize, I know this is a bit contrived but I suspect that this type of thing (needing knowledge of what came after) to be a somewhat common use-case (definitely not a majority use-case, but still).

The only solution I can see is that the workflow user would have to use some external storage in order to keep track of progress, writing to that as it goes and reading from that in order to summarize what occurred in the workflow.
