### ISSUE TITLE
How to define function authorization?

### ISSUE THREAD

**Issue by cdavernas** [serverlessworkflow/specification#318]
**How to define function authentication?**

First of all, big up to all of you, the specification is just awesome.

Second, and even though timing is not perfect (as the spec is not even in RC), I developped my own .NET 5.0 workflow engine for the Serverless Workflow spec, in the context of a cloud native solution for one big member of the CNCF. 
So far so good, I can already define and run very complex workflows, but I recently ran into a big roadblock, conceptually speaking.

As a matter of fact, one of my workflows must invoke REST functions on a out-of-cluster, remote server, which exposes its OpenAPI document on a (poorly) secured endpoint.

I understand that, as opposed to what's explained [here](https://github.com/serverlessworkflow/specification/blob/main/specification.md#Using-Functions-For-RESTful-Service-Invocations), Serverless Workflow does not aim to define/expose non-workflow specific info:

> This approach, however, often runs into issues such as lack of portability, limited capabilities, as well as forcing non-workflow-specific information, such as service authentication, to be added inside the workflow language.

However, as Serverless Workflow specification relies on OpenAPI's for describing functions (which IMHO is a simple, elegant and brilliant idea btw), and that the latter does expose ways to define authorization, is there a way to leverage that? 
If not, **what would you recommend doing for connecting to secured OAS endpoints and to execute secured functions**?

---------------

Here are some ideas that came to my mind will writting this issue:

1. Declare the auth protocol and values to use when executing a function:

```yaml
functions:
    - name: ListPets
      operation:  #OperationDefinition object or string such as 'https://securedendpoint/swagger.json#listPets'
         id: listPets
         definition: https://securedendpoint/swagger.json
         authorization:
            scheme: basic | bearer
            bearer: '${ .token }'
```

2. Declare the auth protocol and values to use when connecting to a secured OAS document

3. Declare and object used to reference external resource files, such as secrets

```yaml
# workflow.yaml
id: MyWorkflow
version: 1.0
name : MyWorkflow
resources:
  - name: SECRETS
    file: mysecrets.json
functions:
    - name: ListPets
      operation:  #OperationDefinition object or string such as 'https://securedendpoint/swagger.json#listPets'
         id: listPets
         definition: https://securedendpoint/swagger.json
         authorization:
            scheme: basic
            username: '$SECRETS.username'
            password: '$SECRETS.password'
...
```
```json
# mysecrets.yaml
{
   "username": "foo@bar.com",
   "password": "foobar"
}
```
The above example would allow securing sensitive data in external resources, and use some convention to use to replace variables defined in workflow.
