### ISSUE TITLE
Directions/ideas on recursive expressions

### ISSUE THREAD

**Issue by Neuroglia** [serverlessworkflow/specification#327]
**What would you like to be added**:

Guidelines on how to enable/handle recursive expressions. Should we even allow those? Or should we use expression-based functions instead?

**Why is this needed**:

Recursive expression resolution, allowing flows such as:

The definition:

```yaml
id: GetAvailablePetsOfCategory
name: GetAvailablePetsOfCategory
description: Retrieves a list of pets and filter them by the petCategory specified as workflow input
version: 1.0.0
functions:
  - name: ListAvailablePets
    operation: https://petstore.swagger.io/v2/swagger.json#findPetsByStatus
states:
  - name: GetAvailablePetsOfCategory
    type: operation
    actions:
       - name: ListAvailablePets
          functionRef:
            refName: ListAvailablePets
            arguments:
              status: available
          actionDataFilter: 
            results: '${ .[] | select(.category.name == ${ .petCategory }) | .id }'
```

The input:

```json
{
   "petCategory": "dogs"
}
```

**Comment by tsurdilo** [comment]
@Neuroglia good point. 
What comes to mind is to use the "fn" reserved keyword to invoke an expression-based function definition, for example;

```text
${ .[] | select(.category.name == fn:getPetCategory }) | .id }
```

note here we would have to clearly describe that the data input to the expression of the actionDataFilter is the results of the function(as it is currently), but the data input of the "getPetCategory" reusable workflow function is the current state data.

Runtimes could pre-parse these expression and substitute the results of fn:getPetCategory with the actual "operation" of the referenced expression type function def. This would allow us to do function chaining of expression functions which would be interesting to say the least. It does put a burned on the runtimes however so lets think about it. 

For now with v0.6 what you can do to have the same result I think as what you are trying to do in your example would be:


```yaml
id: GetAvailablePetsOfCategory
name: GetAvailablePetsOfCategory
description: Retrieves a list of pets and filter them by the petCategory specified
  as workflow input
version: 1.0.0
functions:
- name: ListAvailablePets
  operation: https://petstore.swagger.io/v2/swagger.json#findPetsByStatus
states:
- name: GetAvailablePetsOfCategory
  type: operation
  actions:
  - name: ListAvailablePets
    arguments:
      status: available
    actionDataFilter:
      toStateData: "${ .availablePets }"
  stateDataFilter:
    input: '${ . + {"petCategory": "dog"} }'
    output: "${ .petCategory as $category | .availablePets[] | select(.category.name
      ==  $category)"
```

( you can omit the stateDataFilter "input" if the state has the petCategory already defined in its data input.
The downside of this is that the entire output of the action will be added to the state data and then filtered on the output of the state data filter, rather than being able to be filtered straight up in the action data filter. 

Hope this helps
