### ISSUE TITLE
Please help me understand the expected behavior of keepActive

### ISSUE THREAD

**Issue by kevinteg** [serverlessworkflow/specification#368]
**What is the question**:

I am confused by the keepActive property.  From what I can tell from reading the specification, it allows the workflow to collect data (events, etc) even when there are no active paths.  What are runtimes expected to do with this data when a workflow has this status?

I saw the example that uses keepActive = true ("Room Temp and Humidity Workflow").  Is ConsumeReading supposed to keep receiving and handling events until the execTimeout?  If so, why wouldn't we just transition to ConsumeReading again after receiving the event?

**Comment by tsurdilo** [comment]
Hi Kevin, nice question, it does come up a lot so I will try to give a little bit longer explanation:

From your workflow definition you can create a number of workflow instances. Each instance should be isolated by the runtime impl (meaning has its own execution/run id, cannot share its internal state with other instances, but can still communicate with other instances via events/signals/messages/). 

By default there is a number of situations where a workflow instance is terminated:
a) There are no more active execution paths
b) Explicitly defined "terminate" end definition
c) Defined Workflow execTimeout is reached

Setting keepActive to true changes this behavior a little in that it eliminates option a)

It targets two main cases - long-running workflows and large workflows (eliminates the need for looping structures as you have described).

The example you mentioned is small in order to just showcase the feature but imagine a little larger workflow for example:

<img width="1351" alt="Screen Shot 2021-05-04 at 10 59 45 PM" src="https://user-images.githubusercontent.com/119422/117092508-70595100-ad2c-11eb-9278-0e4f2354009b.png">

and then multiply that by like 10 or 100.

keepActive in these cases allows you to model and maintain your workflow much easier as you don't have to deal with the looping transitions back to event collector state. By just defining one property, you basically eliminate potentially hundreds of lines of json/yaml and alot of headache visualizing and understand and maintaining your definitions.

Another use case (even on a small level) is that you can have a workflow just collect some data once and stay "alive", again without having to write indefinite looping structures. Other workflow instances (of different types) can just query this workflow to get the collected data. This can be useful for scenarios where querying a workflow instance might be faster or cheaper than having to get it from a persistent store many example. 

Btw. this type of behavior is in other workflow lang sometimes called ad-hoc, and in some runtimes where workflow instances are stateful by default, meaning their execution has to be explicitly terminated you can think of keepActive as always set to "true". 

Hope this helps!

**Comment by jorgenj** [comment]
@tsurdilo 

It seems like this is just short-hand so that the workflow writer can avoid making an explicit connection back to the initial start events state, but maybe I'm misunderstanding the point.

Just an idea here but if it's just to avoid that, then could we also achieve this by having a "default transition" declared for a workflow, which would be the transition for any state that doesn't explicitly declare one?

```yaml
name: MyWorkflow
start: S1
defaultTransition: S1
states:
- name: S1
   type: events
   ....
- name: S2
  type: switch
  ....
- name: myOnlyEndState
  ....
  end: true
- name: S3
  type: delay
  # this state would have no transition defined
# 10,000 more states could be defined with no transition, all would effectively loop back to the start, which seems like what this keepActive example is trying to accomplish
- name: S10000
  ...
```
