### ISSUE TITLE
Request more details on function parameters for rest type

### ISSUE THREAD

**Issue by kevinteg** [serverlessworkflow/specification#370]
**What would you like to be added**:

`If you need to define parameters in your functionRef definition, you can define it with its object type which has the following properties:`

I believe the best way to provide arguments for a rest function is all at the same level regardless of whether they are path params, body, etc.  The runtime knows how to associate these parameters to the appropriate request locations based on the OpenAPI spec.  One might argue to explicitly group path params, headers, etc (but I don't think that is necessary).

I'm requesting that we describe the expected behavior of the function and parameters.

For example:
```
  post:
      tags:
        - pet
      summary: Updates a pet in the store with form data
      description: ''
      operationId: updatePetWithForm
      parameters:
        - name: petId
          in: path
          description: ID of pet that needs to be updated
          required: true
          schema:
            type: integer
            format: int64
        - name: name
          in: query
          description: Name of pet that needs to be updated
          schema:
            type: string
        - name: status
          in: query
          description: Status of pet that needs to be updated
          schema:
            type: string
```

The arguments might be:

```
 functionRef:
      refName: updatePet
      arguments:
        petId: 42
        name: Sparky
```

`The workflow will fail if all the required parameters are not specified.  In the example, petId must be specified.`

**Why is this needed**:
This clarifies the expectations for invoking open API calls.

**Comment by tsurdilo** [comment]
Is that currently not possible? 
This is valid:

```yaml
states:
- name: someoperationstate
  type: operation
  actions:
  - functionRef:
      refName: someFunctionRef
      arguments:
        petId: 42
        name: Sparky
  end: true

```

Regarding 
>The workflow will fail if all the required parameters are not specified. In the example, petId must be specified.
Are you asking to add this to the spec? Sorry I am just trying to figure out what the request is.

If so then why "fail the workflow" and what does that even mean? 
First of all, from just looking at the openapi spec and the workflow definition, a validator or an editor can see that missing required params are missing, this error can be reported at compile/validation time.
Second, workflow contains error handling, so even if you dont validate this and it becomes a runtime error, user can add to workflow handling of errors so they can handle it and not just fail. 

We should add this to our sdks I think so users don't have to write it on their own maybe.
