### ISSUE TITLE
Add a top-level "default" correlation property

### ISSUE THREAD

**Issue by cdavernas** [serverlessworkflow/specification#556]
**What would you like to be added**:

A way to specify default correlation keys to be added to all the events produced by workflows.

I was thinking of something of the like:

```yaml
{
"id": "helloworld",
"version": "1.0",
"specVersion": "0.8",
"name": "Hello World Workflow",
"correlation": [
  {
     "contextAttributeName": "correlationId",
     "contextAttributeValue": "1234"
  }
]
```

**Why is this needed**:

When a workflow is instanciated asynchronously by a client, the latter usually needs a way to easily correlate events produced by the instance she has created, based on given discriminator values.
