### ISSUE TITLE
How to consume (and process the data of) a single event?

### ISSUE THREAD

**Issue by cdavernas** [serverlessworkflow/specification#593]
**What is the question**:
How to consume (and process the data of) a single event?

Sometimes, you just need to consume an event without having necessarily triggered anything (aka CallbackState), anywhere, nor having to create a whole new state for doing so (aka EventState).

As we can now atomically produce an event (aka EventRefDefinition with no `consumeEventRef` specified), shouldn't we be able to just consume one, too?

The proposition @tsurdilo (please correct me if I misunderstood you) and I came down to in PM is something like the following:

```yaml
 actions:
    # produces one single event. can do it independently of the consumption. can therefore produce n consecutive events, or just do a traditional callback, etc
    - name: MakeAppointmentAction
      eventRef: 
        refName: MakeVetAppointment #the referenced event definition specifies if we should consume or produce something
        data: "${ .patientInfo }"
    # consumes one single event, allowing to work on the state data (thanks to actionDataFilter) based on a single event, with no forced consequence or cause. For example, reacting to a simple, unbounded notification
    - name: AppointmentConfirmedAction
      eventRef:
        refName: AppointmentConfirmed #the referenced event definition specifies if we should consume or produce something
      actionDataFilter:
        results: "${ .appointmentInfo }"
```

@ricardozanini @mswiderski @antmendoza @yzhao244  WDYT?
