### ISSUE TITLE
Native support for OpenAPI Callback

### ISSUE THREAD

**Issue by EnriqueL8** [serverlessworkflow/specification#605]
**What would you like to be added**:
The OpenAPI specification has this notion of callbacks https://swagger.io/docs/specification/callbacks/. In the context of a workflow, we are considering this as a long-running async request/response.

Currently, SW supports both OpenAPI and AsyncAPI and in the documentation, they tend to suggest using OpenAPI for any sync operations and AsyncAPI for any async operations.  This results in a gap when you consider OpenAPI callbacks mentioned above.

Given an OpenAPI containing a path `/foo` that requires a `callbackURL`,  and a serverless workflow that contains a state calling out to such service we want to continue the workflow when this service calls us back with some payload. i.e 
1. We make an HTTP request to this service
2. We wait for it to call us back with the result. This is not the HTTP response from our request, but a whole new HTTP request performed by the service.
3. We carry on with our workflow

We have tried adapting a workflow definition to this use case: 

Imagine we have a function referencing an OpenAPI operation:
```
functions:
  - name: callbackFoo
     operation: <url-to-my-openapi>#foo
```

NOTE: We are adding the `callbackURL` in the arguments because we are using Kogito and it doesn't support this type of operation.  The OpenAPI client generated by Kogito doesn't allow for configuring the callbackURL in another way.

1) Using an operation state with a timeout 

```
name: CallbackFoo
type: operation
actionMode: sequential
timeouts: 
  stateExecTimeout: PT2S
actions:
- functionRef:
    refName: callbackFoo
    arguments:
      callbackUrl: "${ .callbackUrl }"
      data: "${ .data }"
end: true
```

This does not work because the server will return a `201` automatically and then after some time it will callback to the callbackURL given. We want to wait for that callback to be executed, thus us receiving a new HTTP request with some payload.

2) Using a callback state

```
states:
  - name: callbackFoo
     type: callback
      action:
        name: callbackFoo
        functionRef: 
          refName: callbackFoo
          arguments: 
            inlineObject: "{"callbackUrl": .callbackUrl, \\\"data\\\": {...}}"
      eventRef: callbackFooEvent
      transition: nextState
``` 

Since the OpenAPI callback operation is an async request/response, using the callback state type in SW seems the best fit. But the callback state can only resume after receiving a CloudEvent. OpenAPI does not support CloudEvents natively and thus this OpenAPI callback will not return a CloudEvent but a simple JSON payload. This results in the workflow not resuming.

A possible way forward would be to change the behaviour of the callback state to resume upon receiving a new HTTP request. The resulting HTTP request is documented in the OpenAPI callback section i.e POST/PUT etc... So instead of `eventRef`, we can have a `requestRef` which specifies this specific request we are waiting for.

We are looking for an agreement on the best way to implement this, and as we mentioned above it would impact how Kogito (the runtime we use) would implement this functionality.

@prattyushmangal

**Why is this needed**:

We think that OpenAPI callbacks are a great fit for long-running request/response operations instead of using an event bus for this communication.
