### ISSUE TITLE
Add path templating support

### ISSUE THREAD

**Issue by cdavernas** [serverlessworkflow/specification#648]
**What would you like to be added**:

The ability to render path templates upon functions execution

**Why is this needed**:

So far we have no clean, out-of-box way to make calls to functions which's host name has been defined dynamically.

It is required in cases where you need to make a call to a specific instance of a service, which's url has been returned by a previous call.

Hypothetic example:

```yaml
name: Load Balancer
functions:
- name: get-round-robin-url-for
  type: rest
  operation: https://roundrobin.routing.test.com/openapi.yaml#fastest-url-for
- name: send-email
  operation: https://{emailServiceIP}/openapi.json#send    #resolved dynamiccaly using expression evaluator upon invocation
states:
- name: load-balancer
  type: operation
  actions:
  - name: GetRoundRobinUrlFor
    functionRef:
     refName: get-round-robin-url-for
     arguments:
       serviceName: email
    actionDataFilter:
      toStateData: ${ .emailServiceIP }
  - name: SendEmail
    functionRef:
      refName: send-email
      arguments:
        to: ${ .email.to }
        subject: ${ .email.subject }
        body: ${ .email.body }
 ...
```
