### ISSUE TITLE
Auth definition being able to use $SECRET to avoid hardcoded passwords in file

### ISSUE THREAD

**Issue by fjtirado** [serverlessworkflow/specification#668]
**What would you like to be added**:

In Auth Definition section, explicitly mention that users, rather than hardcode the password string, can use $SECRET (afaik, $SECRET usage is restricted to expressions)

**Why is this needed**:
To avoid hardcoding  passwords, either in the workflow file or the json/yaml file, referenced from the workflow file, containing auth definitions.

**Comment by cdavernas** [comment]
@fjtirado You can already do that, actually, by settings the `properties` of an `authDef` to the secret name.

So, instead of doing:

```yaml
auth:
  - name: MyBasicAuth
    scheme: basic
    properties:
      username: myUserName
      password: ********
```

You can do:

```yaml
auth:
  - name: MyBasicAuth
    scheme: basic
    properties: 'mybasicauthsecret.yaml'
```

**Comment by fjtirado** [comment]
@cdavernas  
Just for verifying we have the same understanding
Which will be the content of mybasicauthsecret.yaml?

**Comment by cdavernas** [comment]
@fjtirado It is expected to match 1:1 on the chosen scheme's properties:

```yaml
{
   "username": "myUserName",
   "password": "MyPassword"
}
```
