### ISSUE TITLE
Rename eventDef correlation properties

### ISSUE THREAD

**Issue by cdavernas** [serverlessworkflow/specification#679]
**What would you like to be added**:

Rename the `eventDef`'s `correlation` object properties to have something shorter, as explicit, and cleaner IMHO.

Currently, we have:

```yaml
...
events:
- name: MyEvent
  kind: consumed
  source: ...
  type: ...
  correlation:
  - contextAttributeName: ...
    contextAttributeValue: ...
...
```

What I propose is to have:

```yaml
...
events:
- name: MyEvent
  kind: consumed
  source: ...
  type: ...
  correlation:
  - name: ...
    value: ...
...
```

**Why is this needed**:

Shorter, cleaner, easier to write without typo/casing mistake, self-explainatory
