### ISSUE TITLE
Move the `validUntil` and `timeZone` properties up to the `Schedule Definition`

### ISSUE THREAD

**Issue by cdavernas** [serverlessworkflow/specification#710]
**What would you like to be added**:

Move the `validUntil` and `timeZone` properties up to the `Schedule Definition`.

So, instead of having this:

```yaml
start:
  schedule:
    cron:
      expression: '* * * * *'
      validUntil: '01/01/2023 10:00 PM'
```

We would have this:

```yaml
start:
  schedule:
    cron: '* * * * *'
    validUntil: '01/01/2023 10:00 PM'
```

In order to allow this:

```yaml
start:
  schedule:
    interval: PT1M
    validUntil: '01/01/2023 10:00 PM'
```

**Why is this needed**:

There is no reason IMHO for not giving to an interval-based schedule the same control on expiration than a CRON-based schedule's.

As a matter of fact, there are use cases where one has to use interval-based schedules and still want the ability to define the date and time at which the schedule expires. This cannot be done out of the box with the current schema.
