### ISSUE TITLE
Rename action `functionRef` property

### ISSUE THREAD

**Issue by cdavernas** [serverlessworkflow/specification#828]
**What would you like to be added**:

Now that we split `eventRef` into two new `subscribe` and `publish` properties, we should rename the `functionRef` into something like `call`, so that we aim at consistently using imperative tense.
We should also rename the `functionRef`'s `refName` property into `function`.

```yaml
actions:
- name: my-action
  call:
    function: greet
    arguments:
      greetings: Hello, World!
```

**Why is this needed**:

- Use cleaner, simpler terminology accross the spec, and avoid at all cost using abbreviations.
- Align with https://github.com/serverlessworkflow/specification/pull/826.
