### ISSUE TITLE
Making task names optional

### ISSUE THREAD

**Issue by fjtirado** [serverlessworkflow/specification#849]
Currently we write

```
execute: 
   tryWith1:
     try: 
         call:
   tryWith2:
      try: 
        call:
```
execute, try and call are reserved words, tryWith1 is a name the user has to came with

If user is lazy and do not want to invent names (which are useful, as far as I know just for `error.instance` feature), he might want to write this instead

```
execute:
  - try: 
    call:
   - try: 
      name: I want to name that one
      call: 

```
