### ISSUE TITLE
Fix the Script Process

### ISSUE THREAD

**Issue by cdavernas** [serverlessworkflow/specification#874]
**What would you like to be added**:

Fix the script process by:

- [x] ~~Document that runtimes **must** support `js` (executed by `NodeJS`) and `python` (executed by `Python`) by default.~~
- [x] ~~Document that `language` should also specify the version (ex: `js:22.2.0`, `python:3`).~~
- [x] Add an `arguments` property, of type `string[]`, used to pass arguments to the script to execute. Document that the arguments can contain runtime expressions.
- [x] Document that `environment` can contain runtime expressions.
- [x] ~~Add an object used to define how the output is read from a script's execution (see below example)~~

*Define script output proposal:*
```yaml
run:
  script:
    language: jq:22.2.0
    code: ...
    output:
      console: {} #indicates that we should read the output from the console (stdout)
      file: {} #indicates that the script is expected to output to a file relative to the script's working directory
      code: {} #indicates that the script outputs its exit code
```

**Why is this needed**:

Allow proper execution of script processes.
