### ISSUE TITLE
Add support for expression objects

### ISSUE THREAD

**Issue by cdavernas** [serverlessworkflow/specification#899]
**What would you like to be added**:

Provide support for using both object and string expressions for `input.from`, `export.as` and `output.as`.

**Why is this needed**:

- Convenience
- Improved readability for complex expressions

*Currently:*
```yaml
...
output: 
  as: '{ style: { shape: "circle", backgroundColor: .colors[0] } }'
```

Proposal:
```yaml
...
output:
  as:
    shape: circle
    style:
      backgroundColor: ${ .colors[0] }
```
