### ISSUE TITLE
Authentication are not referenceable

### ISSUE THREAD

**Issue by cdavernas** [serverlessworkflow/specification#904]
**What seems off**:

Authentication are not referenceable

**What you expected to be**:

Authentications defined at top level should be referenceable

**Anything else we need to know?**:

After discussing the issue with @matthias-pichler-warrify, and well aware than the reference system previously in place was a PITA (oneOf[AuthenticationDefinition, string]), the proposal is something like the following:

```yaml
use:
  authentications:
    basicTest:
      basic:
        username: test
        password: test
do:
  - getPetById:
      call: openapi
      with:
        operationId: getPetById
        parameters:
          id: 69
        authentication: 
          use: basicTest
```

While enabling the same than before, it:
- Avoids oneOf constructs
- Makes consistent use of objects
- Makes the DSL more explicit, fluent and ubiquitous

One a side note, we could instead of `use` name it `ref` or whatever. My strong preference goes to `use`, which is more fluent, understandable, linguistical, is an imperative verb, and is not an abbreviation.
