### ISSUE TITLE
Add additional authority endpoints to OAUTH2

### ISSUE THREAD

**Issue by cdavernas** [serverlessworkflow/specification#912]
**What would you like to be added**:
Add a new property to OAUTH2 authentication, used to define additional token endpoints in order to address https://github.com/serverlessworkflow/synapse/issues/342

**Why is this needed**:
As explained by @jaliyaudagedara in https://github.com/serverlessworkflow/synapse/issues/342, this is a requirement for many librairies when facing authority mismatch

**Comment by cdavernas** [comment]
@ricardozanini @JBBianchi @matthias-pichler-warrify @fjtirado What do you guys think? Can I proceed with it and open a PR?

**Comment by matthias-pichler-warrify** [comment]
Is this in the case where the openId connect configuration lives on a different domain than e.g. the token endpoint?

**Comment by cdavernas** [comment]
Yes, exactly!!!

**Comment by matthias-pichler-warrify** [comment]
Ok got it. What would a proposed solution look like? Because I guess making `authority` an array would mess up the openId discovery right?

On a related note: since OpenID Connect and OAuth2 are separate specifications and many OAuth APIs don't have an OIDC config shouldn't there be a way to specify e.g the token uri directly? And from the fields `client.id` and `client.secret` I guess that only the `client_credentials` flow is supported: what about other flows? (e.g. the legacy `password` flow)

Would it make sense to either:
- add a new `openid` auth type? (probably overkill)
- or extend the `oauth2` auth type to allow more flows and specification fields (like `tokenUri`) that would normally come from an openId config?

**Comment by matthias-pichler-warrify** [comment]
I am actually kind of struggling with the lacking support for oauth right now.

I think a solution should at least cover the following cases:

## Open ID Connect

one can definitely specify a well-known uri to a open id config.

```yaml
document: {}
use:
  authentications:
    exampleOIDC:
      oauth2:
        openIdConnect: https://example.com/.well-known/openid-configuration
        trustedAuthorities:
          - example.net
        grant: client-credentials
        client:
          id: workflow-runtime
          secret: "**********"
       # audience, scopes, etc
```

**Question** @cdavernas is the domain enough to whitelist additional endpoints?

## Token endpoint

```yaml
document: {}
use:
  authentications:
    exampleOIDC:
      oauth2:
        tokenEndpoint: https://example.com/oauth2/token
        grant: client-credentials
        client:
          id: workflow-runtime
          secret: "**********"
       # audience, scopes, etc
```

## Open Questions

1. Content-Type: [RFC 6749](https://datatracker.ietf.org/doc/html/rfc6749#section-4.4.2) states that the access token request body should be `application/x-www-form-urlencoded` encoded, however JSON is also extremely common. Should this be configurable?
2. Authorization: [RFC 6749](https://datatracker.ietf.org/doc/html/rfc6749#section-4.4.2) states that the `client_id` and `client_secret` can be sent via Basic authentication or in the request body ([Section 2.3.1](https://datatracker.ietf.org/doc/html/rfc6749#section-2.3.1)). Some APIs only support one way: should this be configurable?
3. Grant types: Should we support other grant types as well? Specifically the [password grant](https://datatracker.ietf.org/doc/html/rfc6749#section-4.3.1)
