### ISSUE TITLE
Where to find documentation for workflow states?

### ISSUE THREAD

**Issue by sandeep-paliwal** [serverlessworkflow/specification#916]
I was going through [https://github.com/serverlessworkflow/specification/blob/main/dsl-reference.md](https://github.com/serverlessworkflow/specification/blob/main/dsl-reference.md ), but I could not find any details about states , actions and functions. Here is a valid sample workflow JSON and I want to understand what all can go in defining 

1. State
2. Function
3. actions

```json
{
   "id":"Demo1",
   "version":"1.0.0",
   "specVersion":"0.8",
   "name":"Sample Workflow",
   "description":"A sample workflow",
   "start":"Step1",
   "states":[
      {
         "name":"Step1",
         "type":"operation",
         "actions":[
            {
               "functionRef":{
                  "refName":"doSomething"
               }
            }
         ],
         "end":true
      }
   ],
   "functions":[
      {
         "name":"doSomething",
         "operation":"invoke"
      }
   ]
}
```

**Comment by cdavernas** [comment]
@sandeep-paliwal You are not gonna find any documentation regarding `states`, `actions` and  `functions`, because those are opiniated and confusing concepts that do not exist anymore, as they have all been replaced with `tasks`.

Your example would translate as the following in `1.0.0`:

```yaml
document:
  dsl: 1.0.0
  namespace: default
  name: Demo1
  version: 1.0.0
use:
  functions:
    doSomething:
      call: http
      with:
        method: get
        endpoint: https://github.com/serverlessworkflow/specification
do:
  - Step1:
      call: doSomething
```

I would recommend you check both the examples and the CTK in order to further understand the changes the spec went through.

Does that answer your question?

I'm closing the issue, because it is not a bug, problem or feature request. Please feel free, however and if need be, to start a new discussion!
