### ISSUE TITLE
Semantic inconsistencies between `listen` and `emit` tasks

### ISSUE THREAD

**Issue by cdavernas** [serverlessworkflow/specification#917]
**What seems off**:

The `listen` task allows for user to configure events to listen to in the following way:

```yaml
listen:
  to:
    one:
      with: {}
```

Whereas the `emit` task does not define the `with` keyword:

```yaml
emit:
  event: {}
```

**What you expected to be**:

The `emit` task to define a `with` keyword, use to define event properties:

```yaml
emit:
  event:
    with: {}
```

This would allow for potential future properties such as `format`, and would make it more fluent, ubiquitous and consistent.

**Comment by cdavernas** [comment]
@ricardozanini @matthias-pichler-warrify @fjtirado What do you guys think? Should I proceed with it?

**Comment by fjtirado** [comment]
@fjtirado 
I would actually remove with from listen ;), have you considered that approach?

**Comment by fjtirado** [comment]
But yes, if you want to keep with on listen, it makes sense to add it to listen in order to make it symmetric.

**Comment by fjtirado** [comment]
Ok, correcting myself (I did not see the format point) yes, lets add with both for emit and listen. 
Which Im not sure is the usefulness of to: maybe we can just have
```
listen:
   one: 
      with: 

emit: 
  event:
    with:
```
