### ISSUE TITLE
DSL reference Output example

### ISSUE THREAD

**Issue by yzhao244** [serverlessworkflow/specification#934]
In the DSL reference, I noticed the examples of Output component, I don't think I can define "from" and "to" for Output properties, right. If I am not mistaken lol, I can submit PR to correct this example. 

https://github.com/serverlessworkflow/specification/blob/main/dsl-reference.md#output

```
schema:
  format: json
  document:
    type: object
    properties:
      petId:
        type: string
    required: [ petId ]
from:                         ## remove from 
  petId: '${ .pet.id }'   ## remove this line
to: '.petList += [ . ]'   ## replace to with as
```

- Specification version used:
1.0.0-alpha
