### ISSUE TITLE
SwitchTask default case

### ISSUE THREAD

**Issue by JBBianchi** [serverlessworkflow/specification#940]
**What would you like to be added**:
I would like all cases in the [`switch task`](https://github.com/serverlessworkflow/specification/blob/main/schema/workflow.yaml#L563) to define a `when` clause.

**Why is this needed**:
Currently, the `when` clause is optional, allowing the author to define a "default" switch case. While this mirrors regular programming practices, it may not be the best choice for the specification.

The main issue is that every task already has a flow directive, `then`. From a strict perspective:
```yaml
do:
  - decision:
      switch:
        - case1:
            when: .foo == "bar"
            then: doFooBar
        - case2:
            when: .answer == 42
            then: doEverything
        - someOtherCaseNotNamedDefault:
            then: handleUnknownOrderType
```
has four transitions—one for each case plus the omitted `then`. This creates a conflict in decision-making because it’s unclear if the case should take precedence over the task transition.

Additionally, it’s theoretically possible to define more than one case without a `when` clause.

For these reasons, making `when` mandatory and allowing `then` to serve as the default case would be clearer and more straightforward.
