### ISSUE TITLE
Document workflow input when relying on event based schedule

### ISSUE THREAD

**Issue by cdavernas** [serverlessworkflow/specification#977]
**What would you like to be added**:

Document workflow input when relying on event based schedule.

**Why is this needed**:

So far, nothing in the DSL documents what should be done with the event(s) consumed by the event-based schedule of a workflow, which are therefore lost to authors.

**Comment by cdavernas** [comment]
To address that issue we could:

### 1. Pass the workflow events "as is" to the workflow input

If a single event has been consumed, then the input is the single event, otherwise, it is an array of the consumed events.

```yaml
#$workflow.input

#single event
id: 1234
specversion: 1.0
source: https://serverlessworkflow.io
type: io.serverlessworkflow.someevent.v1
data:
  greetings: Hello, World
  
#multiple events
- id: 1234
  specversion: 1.0
  source: https://serverlessworkflow.io
  type: io.serverlessworkflow.someevent.v1
  data:
    greetings: Hello, World
- id: 5678
  specversion: 1.0
  source: https://serverlessworkflow.io
  type: io.serverlessworkflow.someevent.v1
  data:
    greetings: Hello, World
```

If only a single event has been consumed, the user can access it like so:

```jq
$workflow.input
```

If multiple events have been consumed, the user can access one of them like so:

```jq
$workflow.input[0]
```

**Pros**:

- Short
- No additional construct required

**Cons**:

- The author must know ahead of time if a single or multiple events are gonna be consumed

### 2. Pass an object with an `events` property to the workflow input

```yaml
#$workflow.input
events:
- id: 1234
  specversion: 1.0
  source: https://serverlessworkflow.io
  type: io.serverlessworkflow.someevent.v1
  data:
    greetings: Hello, World
- id: 5678
  specversion: 1.0
  source: https://serverlessworkflow.io
  type: io.serverlessworkflow.someevent.v1
  data:
    greetings: Hello, World
```

The user can access input events with an array indexer, regardless of the number of events consumed:

```jq
$workflow.input.events[0]
```

**Pros**:

- Authors can access input events in a consistent fashion

**Cons**:

- Additional construct required
