### ISSUE TITLE
Add a new `until` (optional) property to Event Consumption Strategies of type `any`

### ISSUE THREAD

**Issue by cdavernas** [serverlessworkflow/specification#992]
**What would you like to be added**:

Add a new `until` (optional) property to Event Consumption Strategies of type `any`

**Why is this needed**:

Allows authors to define streaming-like event listeners, that would listen to events until a specific condition is met or until specific events are consumed.

My proposal would allow doing the following:

*Listen to specific events until a runtime expression condition is met:*
```yaml
listen:
  to:
    any: #if no event is defined, all incoming events are matched
      - type: event1
      - type: event2
    until: $context.finishedConsumingEvents
```

*Listen to specific events until the defined event(s) are consumed:*
```yaml
listen:
  to:
    any: {}
  until:
    one:
      with:
        type: io.serverlessworkflow.examples.events.end-listening.v2
```
